"""Turn a :class:`~astrogwb.simulators.spectra.SpectraMetadata` into spectral-density draws.

:class:`SpectrumGenerator` is the generator half of
:func:`astrogwb.simulators.core.simulate`: it builds the live population, waveform
generator and priors a record names, runs
:func:`~astrogwb.inference.draw_spectral_density`, and stamps the result with
the record. It holds only what does not change the draws -- the waveform batch
size -- so two generators with different settings answer the same metadata
with the same file.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import ClassVar

import jax

from astrogwb import __version__
from astrogwb.simulators.spectra.catalog import SpectralDensityCatalog
from astrogwb.simulators.spectra.draws import draw_spectral_density
from astrogwb.simulators.spectra.forward import validate_source_model
from astrogwb.simulators.spectra.metadata import SpectraMetadata

__all__ = ["SpectrumGenerator"]

logger = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class SpectrumGenerator:
    """Draw the spectra a :class:`~astrogwb.simulators.spectra.SpectraMetadata` describes.

    ``batch_size`` chunks the waveform reduction -- peak waveform memory is
    ``(F, batch_size)`` per draw -- and consumes no randomness, which is why it
    lives here and not in the metadata.
    """

    #: What this generator produces, and what :func:`astrogwb.simulators.core.simulate`
    #: loads a cache hit as.
    artifact: ClassVar[type[SpectralDensityCatalog]] = SpectralDensityCatalog

    batch_size: int = 128

    def __post_init__(self) -> None:
        if self.batch_size <= 0:
            raise ValueError("batch_size must be positive")

    def __call__(self, metadata: SpectraMetadata) -> SpectralDensityCatalog:
        """Draw ``metadata``'s spectra and record them against it.

        Values are checked once, eagerly, before the draw: generation is
        trace-safe and trusts its inputs, so a population carrying a degree of
        freedom the approximant cannot represent would otherwise be silently
        dropped.
        """
        # x64 before any array: the rate evaluation and the draws must not
        # depend on ripplegw's import turning it on as a side effect.
        jax.config.update("jax_enable_x64", True)

        if metadata.version != __version__:
            raise ValueError(
                f"metadata is for astrogwb {metadata.version}, but {__version__} "
                "is installed; draws are generated by the code their key names"
            )

        population = metadata.population.build()
        if population.merger_rate_fn is None:
            raise ValueError(
                f"population {metadata.population.model_name!r} declares no "
                "physical merger rate; spectrum generation requires an "
                "observer-frame rate in both count modes"
            )
        generator = metadata.waveform.build()
        priors = {name: spec.build() for name, spec in metadata.sampled.items()}

        rng_key = jax.random.key(metadata.population.seed)
        # One eager source at a representative point: the fixed values, and
        # each prior's mean for the sampled ones.
        validate_source_model(
            {
                **metadata.fixed,
                **{name: float(prior.mean) for name, prior in priors.items()},
            },
            source_model=population.source_model,
            generator=generator,
            rng_key=rng_key,
        )

        logger.info(
            "Spectra %s: count=%s num_events=%s population=%s seed=%d draws=%d "
            "sampled=%s approximant=%s",
            metadata.key(),
            metadata.count,
            metadata.num_events,
            metadata.population.model_name,
            metadata.population.seed,
            metadata.num_draws,
            sorted(priors),
            metadata.waveform.approximant,
        )
        draws = draw_spectral_density(
            source_model=population.source_model,
            merger_rate_fn=population.merger_rate_fn,
            generator=generator,
            hyperparameters={**metadata.fixed, **priors},
            observation_time=metadata.observation_time,
            num_draws=metadata.num_draws,
            rng_key=rng_key,
            batch_size=self.batch_size,
            count=metadata.count,
            num_events=metadata.num_events,
            n_max_sigma=metadata.n_max_sigma,
        )
        return self.artifact.from_draws(draws, metadata)
