[project]
name = "asgwb"
version = "0.1.0"
description = "Constraining cosmology with the SGWB from astrophysical sources"
readme = "README.md"
authors = [
    { name = "binado", email = "bernardopveronese@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "bilby>=2.7.1",
    "h5py>=3.13.0",
    "lalsuite>=7.26.4",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
]

[project.scripts]
asgwb = "asgwb:main"

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]

[tool.pytest.ini_options]
markers = [
    "integration: tests that call external libraries or services (deselect with -m 'not integration')",
]
