import marimo

__generated_with = "0.24.2"
app = marimo.App()

with app.setup(hide_code=True):
    from collections.abc import Mapping, Sequence
    from functools import partial
    from pathlib import Path

    import jax
    import jax.numpy as jnp
    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd
    from matplotlib.axes import Axes as MplAxes
    from matplotlib.figure import Figure
    from matplotlib.lines import Line2D
    from matplotlib.projections import register_projection
    from matplotlib.ticker import LogFormatterMathtext, ScalarFormatter
    from numpyro.infer import Predictive

    from astrogwb.detector import (
        effective_psd,
        load_sensitivity_map,
        log_frequency_noise_scale,
    )
    from astrogwb.frequency import frequency_mask as make_frequency_mask
    from astrogwb.frequency import uniform_grid_spacing
    from astrogwb.gwb import (
        omega_gw_from_spectral_density,
        spectral_snr_squared_per_bin,
        spectral_snr_squared_per_log_frequency,
    )
    from astrogwb.paper.config import (
        fiducials,
        networks,
        population_model,
        waveform_generator,
    )
    from astrogwb.paper.config.runs import FIGURES_DIR
    from astrogwb.paper.plotting import (
        DETECTOR_COMPARISON_LEGEND,
        DETECTOR_NETWORKS,
        SPECTRUM,
        SPECTRUM_LINESTYLES,
        Network,
        detector_network_styles,
        save_figures,
        use_paper_style,
    )
    from astrogwb.sampling import gwb_forward_model
    from astrogwb.utils import years_to_seconds


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    # Plotting the spectral density and network sensitivies

    In this notebook, we plot the spectral density $S_h(f)$ and $\Omega_{\mathrm{GW}}(f)$
    of the gravitational-wave background generated by a population of binary neutron stars.
    We also compare them against the sensitivity different detector network configurations comprised of
    Einstein Telescope (ET) and Cosmic Explorer (CE),
    calculating their expected signal-to-noise ratio (SNR).
    """)
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Notebook configuration
    """)
    return


@app.cell
def _():
    # This file lives in notebooks/, so the repository root is its grandparent.
    # `__file__` is the notebook path under `marimo edit` and when the file is
    # run as a script.
    ROOT_DIR = Path(__file__).resolve().parents[1]

    # gwpy (via gwmock-signal) replaces matplotlib's default rectilinear axes.
    # Restore matplotlib axes so plotting behaves as expected after importing
    # detector utilities.
    register_projection(MplAxes)

    jax.config.update("jax_enable_x64", True)
    use_paper_style(root=ROOT_DIR)

    #: Where this notebook's figures go: under the one output root the workflow,
    #: the figure scripts and `config/plotting.json` all agree on.
    BASE_DIR = ROOT_DIR / FIGURES_DIR / "fiducial_spectrum"

    # The whole fiducial point, from config/fiducials.json: the hyperparameters
    # the draw is taken at, and the H0 the Omega_GW conversion reads. `root=`
    # because the accessors resolve paths against the working directory.
    FIDUCIALS = fiducials(root=ROOT_DIR)

    # Mirrors config/analysis.json. The frequency band is [analysis]; the
    # redshift bounds are analysis.population.model_kwargs. The approximant
    # and observation time are the controls in the next cells.
    minimum_frequency = 2.0
    maximum_frequency = 4096.0
    minimum_redshift = 0.35
    maximum_redshift = 20.0

    # One Poisson draw.
    # batch_size chunks the waveform generation;
    # n_max_sigma sizes the static event plate a Poisson tail above the mean count.
    seed = 41
    batch_size = 1024
    n_max_sigma = 5.0

    # Ordered legend from astrogwb.paper.plotting.DETECTOR_NETWORKS -- a network's
    # label lives there because nothing reads it without the order it sits in --
    # with each detector list resolved through config/networks.json. Order is
    # load-bearing: detector_network_styles assigns a color by first appearance of
    # each base network name, so reordering recolors the curves and breaks the match
    # with the other network figures.
    NETWORK_DETECTORS = networks(root=ROOT_DIR)
    NETWORKS: tuple[Network, ...] = tuple(
        Network(name, label, NETWORK_DETECTORS[name])
        for name, label in DETECTOR_NETWORKS
    )

    # Caps the Omega_GW panels above the signal: the L-shaped networks'
    # calibration-line spikes otherwise stretch the axis to ~1e2.
    OMEGA_GW_MAX: float | None = 1e-4
    CUMULATIVE_SNR_ABOVE_FMINS_HZ = (2.0, 5.0, 10.0, 20.0)
    return (
        BASE_DIR,
        CUMULATIVE_SNR_ABOVE_FMINS_HZ,
        FIDUCIALS,
        NETWORKS,
        OMEGA_GW_MAX,
        ROOT_DIR,
        batch_size,
        maximum_frequency,
        maximum_redshift,
        minimum_frequency,
        minimum_redshift,
        n_max_sigma,
        seed,
    )


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Interactive configuration options
    """)
    return


@app.cell
def _():
    approximant_choice = mo.ui.dropdown(
        options=[
            "TaylorF2",
            "IMRPhenomXAS",
            "IMRPhenomXAS_NRTidalv3",
        ],
        value="IMRPhenomXAS",
        label="Approximant",
    )
    spectrum_choice = mo.ui.dropdown(
        options=["Omega_GW", "S_h"],
        value="Omega_GW",
        label="Plot spectrum",
    )
    # Notebook-only: config/waveform.json is a catalog layer, so its 1 Hz
    # resolution stays put. Finer grids resolve the SNR peak at ~5-10 Hz,
    # where 1 Hz bins leave only a handful of points per e-fold.
    frequency_resolution_choice = mo.ui.dropdown(
        options={"1": 1.0, "0.5": 0.5, "0.25": 0.25, "0.125": 0.125},
        value="0.25",
        label="Frequency resolution (Hz)",
    )
    observation_time_slider = mo.ui.slider(
        start=1,
        stop=10,
        step=1,
        value=1,
        debounce=True,
        show_value=True,
        label="Observation time (years)",
    )
    include_cosmic_explorer_switch = mo.ui.switch(
        value=True,
        label="Include Cosmic Explorer",
    )
    write_figures_switch = mo.ui.switch(
        value=True,
        label="Write figures",
    )
    mo.vstack(
        [
            approximant_choice,
            spectrum_choice,
            frequency_resolution_choice,
            observation_time_slider,
            include_cosmic_explorer_switch,
            write_figures_switch,
        ]
    )
    return (
        approximant_choice,
        frequency_resolution_choice,
        include_cosmic_explorer_switch,
        observation_time_slider,
        spectrum_choice,
        write_figures_switch,
    )


@app.cell
def _(
    approximant_choice,
    frequency_resolution_choice,
    observation_time_slider,
):
    approximant = approximant_choice.value
    frequency_resolution = float(frequency_resolution_choice.value)
    observation_time = float(observation_time_slider.value)
    return approximant, frequency_resolution, observation_time


@app.cell
def _(include_cosmic_explorer_switch):
    include_cosmic_explorer = include_cosmic_explorer_switch.value
    return (include_cosmic_explorer,)


@app.cell
def _(write_figures_switch):
    write_figures = write_figures_switch.value
    return (write_figures,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Plot helpers

    Shared band-limiting and SNR accumulation used by the spectrum panels.
    """)
    return


@app.cell(hide_code=True)
def _():
    def band_limited_spectrum(
        frequencies: jax.Array,
        spectral_density_arr: jax.Array,
        frequency_mask: jax.Array,
        *,
        h0: float,
        effective_psd_arr: jax.Array | np.ndarray | None = None,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray | None]:
        """Restrict $S_h$, $\\Omega_{\\mathrm{GW}}$, and optional $S_{\\mathrm{eff}}$ to the band."""
        omega_gw = omega_gw_from_spectral_density(
            spectral_density_arr,
            frequencies,
            hubble_constant=h0,
        )
        mask = np.asarray(frequency_mask)
        freq = np.asarray(frequencies)[mask]
        omega = np.asarray(omega_gw)[mask]
        sh = np.asarray(spectral_density_arr)[mask]
        pos = (omega > 0.0) & (sh > 0.0) & (freq > 0.0)
        seff: np.ndarray | None = None
        if effective_psd_arr is not None:
            seff = np.asarray(effective_psd_arr)[mask]
            pos = pos & np.isfinite(seff) & (seff > 0.0)
            seff = seff[pos]
        return freq[pos], omega[pos], sh[pos], seff

    def snr_integrand_and_cumulative(
        spectral_density: np.ndarray,
        effective_psd_arr: np.ndarray,
        observation_time_sec: float,
        df: float,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Per-bin $\\Delta\\mathrm{SNR}^2$ and cumulative SNR from the left and right.

        ``SNR(<f)`` and ``SNR(>f)`` both include the bin at ``f``, so the last
        left-hand value and the first right-hand value equal the total SNR. Both
        cumulative curves are divided by that total, mapping them to $[0, 1]$.
        """
        snr_squared = np.asarray(
            spectral_snr_squared_per_bin(
                jnp.asarray(spectral_density),
                jnp.asarray(effective_psd_arr),
                observation_time_sec,
                df,
            )
        )
        snr_lt = np.sqrt(np.cumsum(snr_squared))
        snr_gt = np.sqrt(np.cumsum(snr_squared[::-1])[::-1])
        total = snr_lt[-1]
        return snr_squared, snr_lt / total, snr_gt / total

    def cumulative_snr_above_at(
        frequency: np.ndarray,
        snr_squared: np.ndarray,
        f_cutoff: float,
    ) -> float:
        """Absolute SNR(>f) at the band bin nearest ``f_cutoff``.

        Reuses the same right-cumulative definition as ``snr_integrand_and_cumulative``:
        the bin at ``f`` is included in SNR(>f).
        """
        index = int(np.argmin(np.abs(frequency - f_cutoff)))
        snr_gt = np.sqrt(np.cumsum(snr_squared[::-1])[::-1])
        return float(snr_gt[index])

    def network_legend_handles(
        networks: Sequence[Network],
        colors: Sequence[str],
        linestyles: Sequence[str],
    ) -> list[Line2D]:
        return [
            Line2D([], [], color=color, linestyle=linestyle, label=network.label)
            for network, color, linestyle in zip(
                networks, colors, linestyles, strict=True
            )
        ]

    def format_axis_ticks(axis: MplAxes) -> None:
        """Render tick labels in mathtext / TeX on log and linear axes."""
        if axis.get_xscale() == "log":
            axis.xaxis.set_major_formatter(LogFormatterMathtext())
        else:
            axis.xaxis.set_major_formatter(ScalarFormatter(useMathText=True))
        if axis.get_yscale() == "log":
            axis.yaxis.set_major_formatter(LogFormatterMathtext())
        else:
            axis.yaxis.set_major_formatter(ScalarFormatter(useMathText=True))

    return (
        band_limited_spectrum,
        cumulative_snr_above_at,
        format_axis_ticks,
        network_legend_handles,
        snr_integrand_and_cumulative,
    )


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Simulating the gravitational-wave background
    """)
    return


@app.cell
def _(
    FIDUCIALS,
    ROOT_DIR,
    approximant,
    batch_size,
    frequency_resolution,
    maximum_frequency,
    maximum_redshift,
    minimum_redshift,
    n_max_sigma,
    observation_time,
    seed,
):
    _population = population_model(
        root=ROOT_DIR,
        minimum_redshift=minimum_redshift,
        maximum_redshift=maximum_redshift,
    )
    _merger_rate_fn = _population.merger_rate_fn
    if _merger_rate_fn is None:
        raise ValueError("configured population cannot simulate event counts")

    _generator = waveform_generator(
        root=ROOT_DIR,
        approximant=approximant,
        maximum_frequency=maximum_frequency,
        frequency_resolution=frequency_resolution,
    )
    frequencies = jnp.asarray(_generator.frequencies)

    _rate = float(jnp.asarray(_merger_rate_fn(FIDUCIALS)))
    _mean_count = _rate * years_to_seconds(observation_time)
    _max_events = max(int(np.ceil(_mean_count + n_max_sigma * np.sqrt(_mean_count))), 1)
    _predictive = Predictive(
        partial(
            gwb_forward_model,
            source_model=_population.source_model,
            merger_rate_fn=_merger_rate_fn,
            generator=_generator,
            observation_time=observation_time,
            batch_size=batch_size,
            max_events=_max_events,
        ),
        num_samples=1,
        return_sites=("spectral_density", "n_events", "total_merger_rate"),
    )
    _draw = _predictive(jax.random.key(seed), FIDUCIALS)
    spectral_density = jnp.asarray(_draw["spectral_density"][0])
    _n_events = int(np.asarray(_draw["n_events"]).reshape(-1)[0])

    {"Number of events": _n_events}
    return frequencies, spectral_density


@app.cell
def _(
    FIDUCIALS,
    NETWORKS: tuple[Network, ...],
    band_limited_spectrum,
    frequencies,
    maximum_frequency,
    minimum_frequency,
    observation_time,
    snr_integrand_and_cumulative,
    spectral_density,
):
    _df = uniform_grid_spacing(frequencies)
    frequency_mask = make_frequency_mask(
        frequencies,
        fmin=minimum_frequency,
        fmax=maximum_frequency,
    )

    detector_colors, detector_linestyles = detector_network_styles(NETWORKS)

    effective_psds: dict[str, jax.Array] = {}
    for _network in NETWORKS:
        _sensitivities = load_sensitivity_map(_network.detectors)
        effective_psds[_network.name] = jnp.asarray(
            effective_psd(frequencies, list(_network.detectors), _sensitivities)
        )

    _observation_time_sec = years_to_seconds(observation_time)
    frequency_by_network: dict[str, np.ndarray] = {}
    snr_squared_by_network: dict[str, np.ndarray] = {}
    snr_lt_by_network: dict[str, np.ndarray] = {}
    snr_gt_by_network: dict[str, np.ndarray] = {}
    snr_density_by_network: dict[str, np.ndarray] = {}
    sigma_ln_f_by_network: dict[str, np.ndarray] = {}
    omega_sigma_ln_f_by_network: dict[str, np.ndarray] = {}
    for _network in NETWORKS:
        _band_freq, _, _band_sh, _band_seff = band_limited_spectrum(
            frequencies,
            spectral_density,
            frequency_mask,
            h0=FIDUCIALS["H0"],
            effective_psd_arr=effective_psds[_network.name],
        )
        if _band_seff is None:
            raise RuntimeError(f"{_network.name} effective PSD was not restricted")
        _snr_squared, _snr_lt, _snr_gt = snr_integrand_and_cumulative(
            _band_sh,
            _band_seff,
            _observation_time_sec,
            _df,
        )
        # Per e-fold rather than per bin, so neither curve moves with the grid.
        _sigma_ln_f = np.asarray(
            log_frequency_noise_scale(
                jnp.asarray(_band_seff),
                jnp.asarray(_band_freq),
                observation_time,
            )
        )
        frequency_by_network[_network.name] = _band_freq
        snr_squared_by_network[_network.name] = _snr_squared
        snr_lt_by_network[_network.name] = _snr_lt
        snr_gt_by_network[_network.name] = _snr_gt
        snr_density_by_network[_network.name] = np.asarray(
            spectral_snr_squared_per_log_frequency(
                jnp.asarray(_band_sh),
                jnp.asarray(_band_seff),
                jnp.asarray(_band_freq),
                _observation_time_sec,
            )
        )
        sigma_ln_f_by_network[_network.name] = _sigma_ln_f
        omega_sigma_ln_f_by_network[_network.name] = np.asarray(
            omega_gw_from_spectral_density(
                jnp.asarray(_sigma_ln_f),
                jnp.asarray(_band_freq),
                hubble_constant=FIDUCIALS["H0"],
            )
        )
    fiducial_freq, fiducial_omega, fiducial_sh, _ = band_limited_spectrum(
        frequencies,
        spectral_density,
        frequency_mask,
        h0=FIDUCIALS["H0"],
    )
    return (
        detector_colors,
        detector_linestyles,
        effective_psds,
        fiducial_freq,
        fiducial_omega,
        fiducial_sh,
        frequency_by_network,
        frequency_mask,
        omega_sigma_ln_f_by_network,
        sigma_ln_f_by_network,
        snr_density_by_network,
        snr_gt_by_network,
        snr_lt_by_network,
        snr_squared_by_network,
    )


@app.cell
def _(
    NETWORKS: tuple[Network, ...],
    detector_colors,
    detector_linestyles,
    include_cosmic_explorer,
):
    # Styles stay assigned on the full network tuple, so dropping the CE
    # companions keeps each ET geometry's color.
    if include_cosmic_explorer:
        plotted_networks = NETWORKS
        plotted_colors = detector_colors
        plotted_linestyles = detector_linestyles
    else:
        _kept = tuple(
            (network, color, linestyle)
            for network, color, linestyle in zip(
                NETWORKS,
                detector_colors,
                detector_linestyles,
                strict=True,
            )
            if not network.name.endswith("-CE-Hanford")
        )
        plotted_networks = tuple(network for network, _, _ in _kept)
        plotted_colors = [color for _, color, _ in _kept]
        plotted_linestyles = [linestyle for _, _, linestyle in _kept]
    return plotted_colors, plotted_linestyles, plotted_networks


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Network effective PSDs
    """)
    return


@app.cell
def _(format_axis_ticks, network_legend_handles):
    def plot_effective_psds(
        frequencies: jax.Array,
        networks: Sequence[Network],
        psds_by_network: Mapping[str, jax.Array | np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
        frequency_mask: jax.Array,
    ) -> Figure:
        """Overlay network effective PSDs on shared log–log axes."""
        if len(networks) != len(colors) or len(networks) != len(linestyles):
            raise ValueError("color and linestyle counts must match the networks")

        _fig, ax = plt.subplots()
        mask = np.asarray(frequency_mask)
        freq = np.asarray(frequencies)[mask]
        for network, color, linestyle in zip(networks, colors, linestyles, strict=True):
            psd = np.asarray(psds_by_network[network.name])[mask]
            pos = np.isfinite(psd) & (psd > 0.0) & (freq > 0.0)
            ax.loglog(
                freq[pos],
                psd[pos],
                color=color,
                linestyle=linestyle,
            )

        ax.set_xlabel(r"$f\ \mathrm{(Hz)}$")
        ax.set_ylabel(r"$S_{\mathrm{eff}}(f)\ \mathrm{[Hz^{-1}]}$")
        ax.set_axisbelow(True)
        ax.grid(True, which="both", linestyle=":", linewidth=0.5, alpha=0.5)
        format_axis_ticks(ax)
        ax.legend(
            handles=network_legend_handles(networks, colors, linestyles),
            **DETECTOR_COMPARISON_LEGEND,
        )
        _fig.tight_layout()
        return _fig

    return (plot_effective_psds,)


@app.cell
def _(
    BASE_DIR,
    ROOT_DIR,
    effective_psds: dict[str, jax.Array],
    frequencies,
    frequency_mask,
    plot_effective_psds,
    plotted_colors,
    plotted_linestyles,
    plotted_networks,
    write_figures,
):
    _fig = plot_effective_psds(
        frequencies,
        plotted_networks,
        effective_psds,
        colors=plotted_colors,
        linestyles=plotted_linestyles,
        frequency_mask=frequency_mask,
    )
    if write_figures:
        save_figures({BASE_DIR / "effective_psds.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## $S_h$ versus network sensitivity curves

    The sensitivity curves are $\sigma_{\ln f}(f) = S_{\mathrm{eff}}(f)/\sqrt{2Tf}$:
    the noise over a bandwidth of about $f$, so they do not move with the
    frequency grid. The squared ratio of a spectrum to a curve is
    $d\mathrm{SNR}^2/d\ln f$, plotted below. The likelihood still uses the
    per-bin scale $S_{\mathrm{eff}}/\sqrt{2T\Delta f}$, which is lower by
    $\sqrt{f/\Delta f}$ and so is not a detectability threshold.
    """)
    return


@app.cell
def _(format_axis_ticks, network_legend_handles):
    def draw_spectrum_and_sensitivities(
        ax: MplAxes,
        frequency: np.ndarray,
        spectrum: np.ndarray,
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        sensitivities_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
        spectrum_label: str,
        spectrum_color: str,
        spectrum_linestyle: str,
        ylabel: str,
        ymin: float | None = None,
        ymax: float | None = None,
        include_spectrum_in_legend: bool = True,
        spectrum_legend_loc: str | None = None,
        xlabel: bool = True,
    ) -> None:
        """Overlay a fiducial spectrum with per-network sensitivities on ``ax``.

        When ``spectrum_legend_loc`` is set, the spectrum gets its own legend inside
        the axes (e.g. ``"upper left"``). The network legend still uses
        ``DETECTOR_COMPARISON_LEGEND`` above the frame and remains ``ax.legend_``
        so ``tight_layout`` keeps reserving space for it; the inner legend is
        pinned with ``ax.add_artist``.
        """
        if len(networks) != len(colors) or len(networks) != len(linestyles):
            raise ValueError("color and linestyle counts must match the networks")
        if include_spectrum_in_legend and spectrum_legend_loc is not None:
            raise ValueError(
                "use at most one of include_spectrum_in_legend and spectrum_legend_loc"
            )

        (line_spectrum,) = ax.loglog(
            frequency,
            spectrum,
            color=spectrum_color,
            linestyle=spectrum_linestyle,
            label=spectrum_label,
        )
        for network, color, linestyle in zip(networks, colors, linestyles, strict=True):
            network_frequency = np.asarray(frequency_by_network[network.name])
            sensitivity = np.asarray(sensitivities_by_network[network.name])
            pos = (
                np.isfinite(sensitivity)
                & (sensitivity > 0.0)
                & (network_frequency > 0.0)
            )
            ax.loglog(
                network_frequency[pos],
                sensitivity[pos],
                color=color,
                linestyle=linestyle,
            )

        if xlabel:
            ax.set_xlabel(r"$f\ \mathrm{(Hz)}$")
        ax.set_ylabel(ylabel)
        # Either bound may be pinned; the other keeps its autoscaled value.
        auto_ymin, auto_ymax = ax.get_ylim()
        ax.set_ylim(
            auto_ymin if ymin is None else ymin,
            auto_ymax if ymax is None else ymax,
        )
        ax.set_axisbelow(True)
        ax.grid(True, which="both", linestyle=":", linewidth=0.5, alpha=0.5)
        format_axis_ticks(ax)
        network_handles = network_legend_handles(networks, colors, linestyles)
        legend_handles = (
            [line_spectrum, *network_handles]
            if include_spectrum_in_legend
            else network_handles
        )
        if spectrum_legend_loc is not None:
            # Keep the detector legend as ax.legend_ so tight_layout still
            # accounts for the above-axes bbox; pin the spectrum entry separately.
            spectrum_legend = ax.legend(
                handles=[line_spectrum],
                loc=spectrum_legend_loc,
                frameon=False,
                handlelength=2.5,
            )
            ax.add_artist(spectrum_legend)
        ax.legend(handles=legend_handles, **DETECTOR_COMPARISON_LEGEND)

    return (draw_spectrum_and_sensitivities,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Inspecting the SNR of the spectral density
    """)
    return


@app.cell
def _(
    draw_spectrum_and_sensitivities,
    format_axis_ticks,
    network_legend_handles,
):
    def _draw_snr_curves(
        ax: MplAxes,
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        values_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
        ylabel: str,
        loglog: bool = False,
        legend: bool = True,
    ) -> None:
        """Overlay one per-network SNR curve on ``ax`` and style the axes."""
        if len(networks) != len(colors) or len(networks) != len(linestyles):
            raise ValueError("color and linestyle counts must match the networks")

        draw = ax.loglog if loglog else ax.semilogx
        for network, color, linestyle in zip(networks, colors, linestyles, strict=True):
            draw(
                frequency_by_network[network.name],
                values_by_network[network.name],
                color=color,
                linestyle=linestyle,
            )

        ax.set_xlabel(r"$f\ \mathrm{(Hz)}$")
        ax.set_ylabel(ylabel)
        ax.set_axisbelow(True)
        ax.grid(True, which="both", linestyle=":", linewidth=0.5, alpha=0.5)
        format_axis_ticks(ax)
        if legend:
            ax.legend(
                handles=network_legend_handles(networks, colors, linestyles),
                **DETECTOR_COMPARISON_LEGEND,
            )

    def plot_spectrum_and_snr_density(
        frequency: np.ndarray,
        spectrum: np.ndarray,
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        sensitivities_by_network: Mapping[str, np.ndarray],
        snr_density_by_network: Mapping[str, np.ndarray],
        *,
        observation_time: float,
        colors: Sequence[str],
        linestyles: Sequence[str],
        spectrum_label: str,
        spectrum_color: str,
        spectrum_linestyle: str,
        ylabel: str,
        spectrum_max: float | None = None,
    ) -> Figure:
        """Stack the selected spectrum versus sensitivity over the SNR density.

        The squared gap between the spectrum and a network's curve in the top
        panel is that network's $d\\mathrm{SNR}^2/d\\ln f$ in the bottom one,
        so the shared frequency axis lines the comparison up with where the
        SNR accrues. The density is absolute, so each curve's area is its
        network's $\\mathrm{SNR}^2$ at ``observation_time`` (years), which
        the bottom panel states.
        """
        width, height = plt.rcParams["figure.figsize"]
        _fig, (ax_top, ax_bottom) = plt.subplots(
            2,
            1,
            sharex=True,
            figsize=(width, 1.6 * height),
            gridspec_kw={"height_ratios": (3, 2)},
        )
        draw_spectrum_and_sensitivities(
            ax_top,
            frequency,
            spectrum,
            networks,
            frequency_by_network,
            sensitivities_by_network,
            colors=colors,
            linestyles=linestyles,
            spectrum_label=spectrum_label,
            spectrum_color=spectrum_color,
            spectrum_linestyle=spectrum_linestyle,
            ylabel=ylabel,
            ymax=spectrum_max,
            include_spectrum_in_legend=False,
            spectrum_legend_loc="upper left",
            xlabel=False,
        )
        _draw_snr_curves(
            ax_bottom,
            networks,
            frequency_by_network,
            snr_density_by_network,
            colors=colors,
            linestyles=linestyles,
            ylabel=r"$d\mathrm{SNR}^{2}/d\ln f$",
            legend=False,
        )
        ax_bottom.text(
            0.98,
            0.92,
            rf"$T = {observation_time:g}\ \mathrm{{yr}}$",
            transform=ax_bottom.transAxes,
            ha="right",
            va="top",
        )
        # The bottom panel's semilogx reset the shared x formatter.
        format_axis_ticks(ax_top)
        _fig.tight_layout(h_pad=0.4)
        return _fig

    def plot_snr_integrand(
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        snr_density_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
    ) -> Figure:
        """Plot each network's $d\\mathrm{SNR}^2/d\\ln f$.

        Log x-axis, linear y-axis: the area under a curve over a band is that
        band's share of $\\mathrm{SNR}^2$.
        """
        _fig, ax = plt.subplots()
        _draw_snr_curves(
            ax,
            networks,
            frequency_by_network,
            snr_density_by_network,
            colors=colors,
            linestyles=linestyles,
            ylabel=r"$d\mathrm{SNR}^{2}/d\ln f$",
        )
        _fig.tight_layout()
        return _fig

    def plot_snr_cumulative_below(
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        snr_lt_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
    ) -> Figure:
        """Plot each network's SNR accumulated from the low-frequency end."""
        _fig, ax = plt.subplots()
        _draw_snr_curves(
            ax,
            networks,
            frequency_by_network,
            snr_lt_by_network,
            colors=colors,
            linestyles=linestyles,
            ylabel=r"$\mathrm{SNR}(<f) / \mathrm{SNR}_{\mathrm{tot}}$",
        )
        _fig.tight_layout()
        return _fig

    def plot_snr_cumulative_above(
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        snr_gt_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
    ) -> Figure:
        """Plot each network's SNR accumulated from the high-frequency end."""
        _fig, ax = plt.subplots()
        _draw_snr_curves(
            ax,
            networks,
            frequency_by_network,
            snr_gt_by_network,
            colors=colors,
            linestyles=linestyles,
            ylabel=r"$\mathrm{SNR}(>f) / \mathrm{SNR}_{\mathrm{tot}}$",
        )
        _fig.tight_layout()
        return _fig

    return (
        plot_snr_cumulative_above,
        plot_snr_cumulative_below,
        plot_snr_integrand,
        plot_spectrum_and_snr_density,
    )


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ### Plotting the SNR density per e-fold of frequency

    $d\mathrm{SNR}^2/d\ln f = 2Tf\,S_h^2/S_{\mathrm{eff}}^2$ on a log
    frequency axis and a linear y-axis, so equal areas are equal contributions
    to $\mathrm{SNR}^2$ and the curve does not depend on the frequency grid.
    """)
    return


@app.cell
def _(
    BASE_DIR,
    ROOT_DIR,
    frequency_by_network: dict[str, np.ndarray],
    plot_snr_integrand,
    plotted_colors,
    plotted_linestyles,
    plotted_networks,
    snr_density_by_network: dict[str, np.ndarray],
    write_figures,
):
    _fig = plot_snr_integrand(
        plotted_networks,
        frequency_by_network,
        snr_density_by_network,
        colors=plotted_colors,
        linestyles=plotted_linestyles,
    )
    if write_figures:
        save_figures({BASE_DIR / "snr_integrand.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ### Network sensitivity and SNR density, stacked

    The paper figure: the configured spectrum against each network's
    $\sigma_{\ln f}$ on top, and below it $d\mathrm{SNR}^2/d\ln f$, whose
    area in $\ln f$ is each network's $\mathrm{SNR}^2$ at the chosen
    observation time. The ET geometries share nearly one shape, so the curves
    separate by amplitude; the dashed +CE curves also extend to 10--30 Hz.
    """)
    return


@app.cell
def _(
    BASE_DIR,
    OMEGA_GW_MAX: float | None,
    ROOT_DIR,
    fiducial_freq,
    fiducial_omega,
    fiducial_sh,
    frequency_by_network: dict[str, np.ndarray],
    observation_time,
    omega_sigma_ln_f_by_network: dict[str, np.ndarray],
    plot_spectrum_and_snr_density,
    plotted_colors,
    plotted_linestyles,
    plotted_networks,
    sigma_ln_f_by_network: dict[str, np.ndarray],
    snr_density_by_network: dict[str, np.ndarray],
    spectrum_choice,
    write_figures,
):
    if spectrum_choice.value == "Omega_GW":
        _spectrum = fiducial_omega
        _sensitivities = omega_sigma_ln_f_by_network
        _spectrum_label = r"$\Omega_{\mathrm{GW}}$"
        _spectrum_color = SPECTRUM["omega_gw"]
        _spectrum_linestyle = ":"
        _ylabel = r"$\Omega_{\mathrm{GW}}(f), \, \sigma_{\ln f}(f)$"
        _spectrum_max = OMEGA_GW_MAX
        _filename = "omega_sensitivity_and_snr_density.pdf"
    else:
        _spectrum = fiducial_sh
        _sensitivities = sigma_ln_f_by_network
        _spectrum_label = r"$S_h$"
        _spectrum_color = SPECTRUM["sh"]
        _spectrum_linestyle = SPECTRUM_LINESTYLES["sh"]
        _ylabel = r"$S_h(f), \, \sigma_{\ln f}(f)\ \mathrm{[Hz^{-1}]}$"
        _spectrum_max = None
        _filename = "sh_sensitivity_and_snr_density.pdf"

    _fig = plot_spectrum_and_snr_density(
        fiducial_freq,
        _spectrum,
        plotted_networks,
        frequency_by_network,
        _sensitivities,
        snr_density_by_network,
        observation_time=observation_time,
        colors=plotted_colors,
        linestyles=plotted_linestyles,
        spectrum_label=_spectrum_label,
        spectrum_color=_spectrum_color,
        spectrum_linestyle=_spectrum_linestyle,
        ylabel=_ylabel,
        spectrum_max=_spectrum_max,
    )
    if write_figures:
        save_figures(
            {BASE_DIR / _filename: _fig},
            root=ROOT_DIR,
        )
    _fig
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ### Plotting the fraction of SNR below a given frequency
    """)
    return


@app.cell
def _(
    BASE_DIR,
    ROOT_DIR,
    frequency_by_network: dict[str, np.ndarray],
    plot_snr_cumulative_below,
    plotted_colors,
    plotted_linestyles,
    plotted_networks,
    snr_lt_by_network: dict[str, np.ndarray],
    write_figures,
):
    _fig = plot_snr_cumulative_below(
        plotted_networks,
        frequency_by_network,
        snr_lt_by_network,
        colors=plotted_colors,
        linestyles=plotted_linestyles,
    )
    if write_figures:
        save_figures({BASE_DIR / "snr_cumulative_below.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ### Plotting the fraction of SNR above a given frequency
    """)
    return


@app.cell
def _(
    BASE_DIR,
    ROOT_DIR,
    frequency_by_network: dict[str, np.ndarray],
    plot_snr_cumulative_above,
    plotted_colors,
    plotted_linestyles,
    plotted_networks,
    snr_gt_by_network: dict[str, np.ndarray],
    write_figures,
):
    _fig = plot_snr_cumulative_above(
        plotted_networks,
        frequency_by_network,
        snr_gt_by_network,
        colors=plotted_colors,
        linestyles=plotted_linestyles,
    )
    if write_figures:
        save_figures({BASE_DIR / "snr_cumulative_above.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## Dependence of the SNR on the low-frequency cutoff $f_\mathrm{min}$

    Absolute $\mathrm{SNR}(>f)$ at $f = 2, 5, 10, 20\ \mathrm{Hz}$ for each
    detector network. Values come from the same right-cumulative sum as the
    normalized curves above, evaluated at the band bin nearest each cutoff.
    """)
    return


@app.cell
def _(cumulative_snr_above_at):
    def build_cumulative_snr_above_table(
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        snr_squared_by_network: Mapping[str, np.ndarray],
        f_cutoffs_hz: Sequence[float],
    ) -> tuple[pd.DataFrame, str]:
        """Tabulate absolute SNR(>f) at each cutoff for every network."""
        rows: list[dict[str, float | str]] = []
        for network in networks:
            frequency = frequency_by_network[network.name]
            snr_squared = snr_squared_by_network[network.name]
            row: dict[str, float | str] = {
                "Detector Network": rf"{network.label}",
            }
            for f_cutoff in f_cutoffs_hz:
                row[f"SNR above {f_cutoff:g} Hz"] = cumulative_snr_above_at(
                    frequency,
                    snr_squared,
                    f_cutoff,
                )
            rows.append(row)

        df = pd.DataFrame(rows)
        df.set_index("Detector Network", inplace=True)
        latex_table = df.to_latex(
            index=True,
            escape=False,
            float_format="%.2g",
            caption=(
                "Matched-filter SNR accumulated above $f$ for each detector network "
                "at the fiducial injection."
            ),
            label="tab:fiducial_cumulative_snr_above",
        )
        return df, latex_table

    return (build_cumulative_snr_above_table,)


@app.cell
def _(
    CUMULATIVE_SNR_ABOVE_FMINS_HZ,
    build_cumulative_snr_above_table,
    frequency_by_network: dict[str, np.ndarray],
    plotted_networks,
    snr_squared_by_network: dict[str, np.ndarray],
):
    cumulative_snr_above_table, latex_table = build_cumulative_snr_above_table(
        plotted_networks,
        frequency_by_network,
        snr_squared_by_network,
        CUMULATIVE_SNR_ABOVE_FMINS_HZ,
    )
    cumulative_snr_above_table
    return (latex_table,)


@app.cell
def _(BASE_DIR, latex_table, write_figures):
    if write_figures:
        BASE_DIR.mkdir(parents=True, exist_ok=True)
        _cumulative_snr_above_tex_path = BASE_DIR / "cumulative_snr_above.tex"
        _cumulative_snr_above_tex_path.write_text(
            latex_table,
            encoding="utf-8",
        )
        print("saved:", _cumulative_snr_above_tex_path)
    return


if __name__ == "__main__":
    app.run()
