import marimo

__generated_with = "0.24.2"
app = marimo.App()

with app.setup:
    from collections.abc import Mapping, Sequence
    from functools import partial
    from pathlib import Path

    import jax
    import jax.numpy as jnp
    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np
    import pandas as pd
    from matplotlib.axes import Axes as MplAxes
    from matplotlib.figure import Figure
    from matplotlib.lines import Line2D
    from matplotlib.projections import register_projection
    from matplotlib.ticker import LogFormatterMathtext, ScalarFormatter
    from numpyro.infer import Predictive

    from astrogwb.detector import (
        effective_psd,
        gaussian_bin_scale,
        load_sensitivity_map,
    )
    from astrogwb.frequency import frequency_mask as make_frequency_mask
    from astrogwb.frequency import uniform_grid_spacing
    from astrogwb.gwb import (
        omega_gw_from_spectral_density,
        spectral_snr_squared_per_bin,
    )
    from astrogwb.paper.config import (
        fiducials,
        networks,
        population_model,
        waveform_generator,
    )
    from astrogwb.paper.config.runs import FIGURES_DIR
    from astrogwb.paper.plotting import (
        DETECTOR_COMPARISON_LEGEND,
        DETECTOR_NETWORKS,
        SPECTRUM,
        SPECTRUM_LINESTYLES,
        Network,
        detector_network_styles,
        save_figures,
        use_paper_style,
    )
    from astrogwb.sampling import gwb_forward_model
    from astrogwb.utils import years_to_seconds


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Plotting the spectral density and network sensitivies

    In this notebook, we plot the spectral density $S_h(f)$ and $\Omega_{\mathrm{GW}}(f)$
    of the gravitational-wave background generated by a population of binary neutron stars.
    We also compare them against the sensitivity different detector network configurations comprised of
    Einstein Telescope (ET) and Cosmic Explorer (CE),
    calculating their expected signal-to-noise ratio (SNR).
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Notebook configuration
    """)
    return


@app.cell
def _(
    DETECTOR_NETWORKS,
    FIGURES_DIR,
    MplAxes,
    Network,
    Path,
    fiducials,
    jax,
    networks,
    register_projection,
    use_paper_style,
):
    # This file lives in notebooks/, so the repository root is its grandparent.
    # `__file__` is the notebook path under `marimo edit` and when the file is
    # run as a script.
    ROOT_DIR = Path(__file__).resolve().parents[1]

    # gwpy (via gwmock-signal) replaces matplotlib's default rectilinear axes.
    # Restore matplotlib axes so plotting behaves as expected after importing
    # detector utilities.
    register_projection(MplAxes)

    jax.config.update("jax_enable_x64", True)
    use_paper_style(root=ROOT_DIR)

    #: Where this notebook's figures go: under the one output root the workflow,
    #: the figure scripts and `config/plotting.json` all agree on.
    BASE_DIR = ROOT_DIR / FIGURES_DIR / "fiducial_spectrum"

    # The whole fiducial point, from config/fiducials.json: the hyperparameters
    # the draw is taken at, and the H0 the Omega_GW conversion reads. `root=`
    # because the accessors resolve paths against the working directory.
    FIDUCIALS = fiducials(root=ROOT_DIR)

    # Mirrors config/analysis.json. observation_time and the frequency band are
    # [analysis]; the redshift bounds are analysis.population.model_kwargs.
    observation_time = 1.0
    minimum_frequency = 2.0
    maximum_frequency = 4096.0
    minimum_redshift = 0.35
    maximum_redshift = 20.0

    approximant = "IMRPhenomXAS"

    # One Poisson draw.
    # batch_size chunks the waveform generation;
    # n_max_sigma sizes the static event plate a Poisson tail above the mean count.
    seed = 41
    batch_size = 1024
    n_max_sigma = 5.0

    # Ordered legend from astrogwb.paper.plotting.DETECTOR_NETWORKS -- a network's
    # label lives there because nothing reads it without the order it sits in --
    # with each detector list resolved through config/networks.json. Order is
    # load-bearing: detector_network_styles assigns a color by first appearance of
    # each base network name, so reordering recolors the curves and breaks the match
    # with the other network figures.
    NETWORK_DETECTORS = networks(root=ROOT_DIR)
    NETWORKS: tuple[Network, ...] = tuple(
        Network(name, label, NETWORK_DETECTORS[name])
        for name, label in DETECTOR_NETWORKS
    )
    REFERENCE_NETWORK = "ET-2L-aligned-CE-Hanford"

    OMEGA_GW_MIN: float | None = None
    CUMULATIVE_SNR_ABOVE_FMINS_HZ = (2.0, 5.0, 10.0, 20.0)

    # Cumulative-SNR curves on the stacked figure: Okabe-Ito blue / vermillion,
    # distinct from the black dual-axis spectrum.
    SNR_LT_COLOR = "#0072B2"
    SNR_GT_COLOR = "#D55E00"
    SNR_LT_LINESTYLE = "-"
    SNR_GT_LINESTYLE = "--"
    return (
        BASE_DIR,
        CUMULATIVE_SNR_ABOVE_FMINS_HZ,
        FIDUCIALS,
        NETWORKS,
        NETWORK_DETECTORS,
        OMEGA_GW_MIN,
        REFERENCE_NETWORK,
        ROOT_DIR,
        SNR_GT_COLOR,
        SNR_GT_LINESTYLE,
        SNR_LT_COLOR,
        SNR_LT_LINESTYLE,
        approximant,
        batch_size,
        maximum_frequency,
        maximum_redshift,
        minimum_frequency,
        minimum_redshift,
        n_max_sigma,
        observation_time,
        seed,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Plot helpers

    Shared band-limiting, SNR accumulation, and the dual-axis $S_h$ /
    $\Omega_{\mathrm{GW}}$ drawing used by the spectrum panels.
    """)
    return


@app.cell
def _(
    Line2D,
    LogFormatterMathtext,
    MplAxes,
    Network,
    SPECTRUM,
    SPECTRUM_LINESTYLES,
    ScalarFormatter,
    Sequence,
    jax,
    jnp,
    np,
    omega_gw_from_spectral_density,
    spectral_snr_squared_per_bin,
):
    def sh_ymin_matching_omega_floor(
        omega_gw: np.ndarray,
        spectral_density_arr: np.ndarray,
        omega_gw_min: float | None = None,
    ) -> float | None:
        """Infer $S_h$ ymin from the frequency where $\\Omega_{\\mathrm{GW}}$ hits its floor.

        Defaults to ``None``, which means no floor: the caller should leave the
        axis autoscaled.
        """
        if omega_gw_min is None:
            return None
        if omega_gw_min <= 0.0:
            raise ValueError(f"omega_gw_min must be positive, got {omega_gw_min}")
        if omega_gw.size == 0:
            raise ValueError("cannot infer S_h ymin from an empty spectrum")
        index = int(np.argmin(np.abs(np.log(omega_gw) - np.log(omega_gw_min))))
        return float(spectral_density_arr[index])

    def band_limited_spectrum(
        frequencies: jax.Array,
        spectral_density_arr: jax.Array,
        frequency_mask: jax.Array,
        *,
        h0: float,
        effective_psd_arr: jax.Array | np.ndarray | None = None,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray | None]:
        """Restrict $S_h$, $\\Omega_{\\mathrm{GW}}$, and optional $S_{\\mathrm{eff}}$ to the band."""
        omega_gw = omega_gw_from_spectral_density(
            spectral_density_arr,
            frequencies,
            hubble_constant=h0,
        )
        mask = np.asarray(frequency_mask)
        freq = np.asarray(frequencies)[mask]
        omega = np.asarray(omega_gw)[mask]
        sh = np.asarray(spectral_density_arr)[mask]
        pos = (omega > 0.0) & (sh > 0.0) & (freq > 0.0)
        seff: np.ndarray | None = None
        if effective_psd_arr is not None:
            seff = np.asarray(effective_psd_arr)[mask]
            pos = pos & np.isfinite(seff) & (seff > 0.0)
            seff = seff[pos]
        return freq[pos], omega[pos], sh[pos], seff

    def snr_integrand_and_cumulative(
        spectral_density: np.ndarray,
        effective_psd_arr: np.ndarray,
        observation_time_sec: float,
        df: float,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Per-bin $\\Delta\\mathrm{SNR}^2$ and cumulative SNR from the left and right.

        ``SNR(<f)`` and ``SNR(>f)`` both include the bin at ``f``, so the last
        left-hand value and the first right-hand value equal the total SNR. Both
        cumulative curves are divided by that total, mapping them to $[0, 1]$.
        """
        snr_squared = np.asarray(
            spectral_snr_squared_per_bin(
                jnp.asarray(spectral_density),
                jnp.asarray(effective_psd_arr),
                observation_time_sec,
                df,
            )
        )
        snr_lt = np.sqrt(np.cumsum(snr_squared))
        snr_gt = np.sqrt(np.cumsum(snr_squared[::-1])[::-1])
        total = snr_lt[-1]
        return snr_squared, snr_lt / total, snr_gt / total

    def cumulative_snr_above_at(
        frequency: np.ndarray,
        snr_squared: np.ndarray,
        f_cutoff: float,
    ) -> float:
        """Absolute SNR(>f) at the band bin nearest ``f_cutoff``.

        Reuses the same right-cumulative definition as ``snr_integrand_and_cumulative``:
        the bin at ``f`` is included in SNR(>f).
        """
        index = int(np.argmin(np.abs(frequency - f_cutoff)))
        snr_gt = np.sqrt(np.cumsum(snr_squared[::-1])[::-1])
        return float(snr_gt[index])

    def network_legend_handles(
        networks: Sequence[Network],
        colors: Sequence[str],
        linestyles: Sequence[str],
    ) -> list[Line2D]:
        return [
            Line2D([], [], color=color, linestyle=linestyle, label=network.label)
            for network, color, linestyle in zip(
                networks, colors, linestyles, strict=True
            )
        ]

    def format_axis_ticks(axis: MplAxes) -> None:
        """Render tick labels in mathtext / TeX on log and linear axes."""
        if axis.get_xscale() == "log":
            axis.xaxis.set_major_formatter(LogFormatterMathtext())
        else:
            axis.xaxis.set_major_formatter(ScalarFormatter(useMathText=True))
        if axis.get_yscale() == "log":
            axis.yaxis.set_major_formatter(LogFormatterMathtext())
        else:
            axis.yaxis.set_major_formatter(ScalarFormatter(useMathText=True))

    def _spectrum_line_styles(
        *,
        omega_color: str | None,
        sh_color: str | None,
        omega_linestyle: str | None,
        sh_linestyle: str | None,
    ) -> tuple[str, str, str, str]:
        if omega_color is None:
            omega_color = SPECTRUM["omega_gw"]
        if sh_color is None:
            sh_color = SPECTRUM["sh"]
        if omega_linestyle is None:
            omega_linestyle = SPECTRUM_LINESTYLES["omega_gw"]
        if sh_linestyle is None:
            sh_linestyle = SPECTRUM_LINESTYLES["sh"]
        return omega_color, sh_color, omega_linestyle, sh_linestyle

    def draw_omega_and_sh(
        ax_sh: MplAxes,
        frequency: np.ndarray,
        omega_gw: np.ndarray,
        spectral_density: np.ndarray,
        *,
        omega_gw_min: float | None = None,
        ax_omega: MplAxes | None = None,
        omega_color: str | None = None,
        sh_color: str | None = None,
        omega_linestyle: str | None = None,
        sh_linestyle: str | None = None,
        xlabel: bool = True,
        legend: bool = True,
    ) -> tuple[MplAxes, Line2D, Line2D]:
        """Draw dual-axis $S_h$ / $\\Omega_{\\mathrm{GW}}$ onto ``ax_sh``.

        A numeric ``omega_gw_min`` pins both y-axes to that floor. The default
        ``None`` leaves them autoscaled.
        """
        axis_color = "k"
        omega_color, sh_color, omega_linestyle, sh_linestyle = _spectrum_line_styles(
            omega_color=omega_color,
            sh_color=sh_color,
            omega_linestyle=omega_linestyle,
            sh_linestyle=sh_linestyle,
        )
        if ax_omega is None:
            ax_omega = ax_sh.twinx()

        (line_sh,) = ax_sh.loglog(
            frequency,
            spectral_density,
            color=sh_color,
            linestyle=sh_linestyle,
            label=r"$S_h$",
        )
        (line_omega,) = ax_omega.loglog(
            frequency,
            omega_gw,
            color=omega_color,
            linestyle=omega_linestyle,
            label=r"$\Omega_{\mathrm{GW}}$",
        )

        if xlabel:
            ax_sh.set_xlabel(r"$f\ \mathrm{(Hz)}$", color=axis_color)
        ax_sh.set_ylabel(r"$S_h(f)\ \mathrm{[Hz^{-1}]}$", color=axis_color)
        ax_omega.set_ylabel(r"$\Omega_{\mathrm{GW}}(f)$", color=axis_color)
        ax_sh.tick_params(axis="x", colors=axis_color)
        ax_sh.tick_params(axis="y", colors=axis_color)
        ax_omega.tick_params(axis="y", colors=axis_color)
        for axis in (ax_sh, ax_omega):
            for spine in axis.spines.values():
                spine.set_color(axis_color)
        if omega_gw_min is not None:
            sh_ymin = sh_ymin_matching_omega_floor(
                omega_gw, spectral_density, omega_gw_min
            )
            _, ymax = ax_sh.get_ylim()
            ax_sh.set_ylim(sh_ymin, ymax)
            ax_omega.set_ylim(omega_gw_min, None)
        ax_sh.set_axisbelow(True)
        ax_sh.grid(True, which="both", linestyle=":", linewidth=0.5, alpha=0.5)
        ax_omega.grid(False)
        format_axis_ticks(ax_sh)
        format_axis_ticks(ax_omega)
        if legend:
            ax_sh.legend(
                handles=[line_sh, line_omega],
                loc="upper right",
                frameon=False,
                handlelength=2.5,
            )
        return ax_omega, line_sh, line_omega

    return (
        band_limited_spectrum,
        cumulative_snr_above_at,
        draw_omega_and_sh,
        format_axis_ticks,
        network_legend_handles,
        sh_ymin_matching_omega_floor,
        snr_integrand_and_cumulative,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Simulating the gravitational-wave background
    """)
    return


@app.cell
def _(
    FIDUCIALS,
    NETWORKS,
    Predictive,
    REFERENCE_NETWORK,
    ROOT_DIR,
    approximant,
    band_limited_spectrum,
    batch_size,
    detector_network_styles,
    effective_psd,
    gaussian_bin_scale,
    gwb_forward_model,
    jax,
    jnp,
    load_sensitivity_map,
    make_frequency_mask,
    maximum_frequency,
    maximum_redshift,
    minimum_frequency,
    minimum_redshift,
    n_max_sigma,
    np,
    observation_time,
    omega_gw_from_spectral_density,
    partial,
    population_model,
    seed,
    snr_integrand_and_cumulative,
    uniform_grid_spacing,
    waveform_generator,
    years_to_seconds,
):
    _population = population_model(
        root=ROOT_DIR,
        minimum_redshift=minimum_redshift,
        maximum_redshift=maximum_redshift,
    )
    _merger_rate_fn = _population.merger_rate_fn
    if _merger_rate_fn is None:
        raise ValueError("configured population cannot simulate event counts")

    _generator = waveform_generator(
        root=ROOT_DIR,
        approximant=approximant,
        maximum_frequency=maximum_frequency,
    )

    _rate = float(jnp.asarray(_merger_rate_fn(FIDUCIALS)))
    _mean_count = _rate * years_to_seconds(observation_time)
    _max_events = max(int(np.ceil(_mean_count + n_max_sigma * np.sqrt(_mean_count))), 1)
    _predictive = Predictive(
        partial(
            gwb_forward_model,
            source_model=_population.source_model,
            merger_rate_fn=_merger_rate_fn,
            generator=_generator,
            observation_time=observation_time,
            batch_size=batch_size,
            max_events=_max_events,
        ),
        num_samples=1,
        return_sites=("spectral_density", "n_events", "total_merger_rate"),
    )
    _draw = _predictive(jax.random.key(seed), FIDUCIALS)
    spectral_density = jnp.asarray(_draw["spectral_density"][0])
    _n_events = int(np.asarray(_draw["n_events"]).reshape(-1)[0])

    frequencies = jnp.asarray(_generator.frequencies)
    _df = uniform_grid_spacing(frequencies)
    frequency_mask = make_frequency_mask(
        frequencies,
        fmin=minimum_frequency,
        fmax=maximum_frequency,
    )

    _reference_network = next(
        _network for _network in NETWORKS if _network.name == REFERENCE_NETWORK
    )
    detector_colors, detector_linestyles = detector_network_styles(NETWORKS)

    effective_psds: dict[str, jax.Array] = {}
    for _network in NETWORKS:
        _sensitivities = load_sensitivity_map(_network.detectors)
        effective_psds[_network.name] = jnp.asarray(
            effective_psd(frequencies, list(_network.detectors), _sensitivities)
        )

    _observation_time_sec = years_to_seconds(observation_time)
    frequency_by_network: dict[str, np.ndarray] = {}
    snr_squared_by_network: dict[str, np.ndarray] = {}
    snr_lt_by_network: dict[str, np.ndarray] = {}
    snr_gt_by_network: dict[str, np.ndarray] = {}
    sigma_by_network: dict[str, np.ndarray] = {}
    omega_sigma_by_network: dict[str, np.ndarray] = {}
    _reference_band: tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray] | None = None
    for _network in NETWORKS:
        _band_freq, _band_omega, _band_sh, _band_seff = band_limited_spectrum(
            frequencies,
            spectral_density,
            frequency_mask,
            h0=FIDUCIALS["H0"],
            effective_psd_arr=effective_psds[_network.name],
        )
        if _band_seff is None:
            raise RuntimeError(f"{_network.name} effective PSD was not restricted")
        _snr_squared, _snr_lt, _snr_gt = snr_integrand_and_cumulative(
            _band_sh,
            _band_seff,
            _observation_time_sec,
            _df,
        )
        _sigma = np.asarray(
            gaussian_bin_scale(jnp.asarray(_band_seff), observation_time, _df)
        )
        frequency_by_network[_network.name] = _band_freq
        snr_squared_by_network[_network.name] = _snr_squared
        snr_lt_by_network[_network.name] = _snr_lt
        snr_gt_by_network[_network.name] = _snr_gt
        sigma_by_network[_network.name] = _sigma
        omega_sigma_by_network[_network.name] = np.asarray(
            omega_gw_from_spectral_density(
                jnp.asarray(_sigma),
                jnp.asarray(_band_freq),
                hubble_constant=FIDUCIALS["H0"],
            )
        )
        if _network.name == _reference_network.name:
            _reference_band = (_band_freq, _band_omega, _band_sh, _band_seff)
    if _reference_band is None:
        raise RuntimeError("reference-network spectrum was not computed")
    fiducial_freq, fiducial_omega, fiducial_sh, _ = band_limited_spectrum(
        frequencies,
        spectral_density,
        frequency_mask,
        h0=FIDUCIALS["H0"],
    )
    print(
        f"simulated spectrum: n_frequency_bins={frequencies.shape[0]} "
        f"n_events={_n_events} max_events={_max_events}"
    )
    print(
        "band bins:",
        int(np.sum(np.asarray(frequency_mask))),
        "of",
        frequencies.shape[0],
    )
    print("reference network:", _reference_network.label)
    return (
        detector_colors,
        detector_linestyles,
        effective_psds,
        fiducial_freq,
        fiducial_omega,
        fiducial_sh,
        frequencies,
        frequency_by_network,
        frequency_mask,
        omega_sigma_by_network,
        sigma_by_network,
        snr_gt_by_network,
        snr_lt_by_network,
        snr_squared_by_network,
        spectral_density,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Fiducial $S_h$ and $\Omega_{\mathrm{GW}}$
    """)
    return


@app.cell
def _(Figure, band_limited_spectrum, draw_omega_and_sh, jax, plt):
    def plot_omega_and_sh(
        frequencies: jax.Array,
        spectral_density_arr: jax.Array,
        frequency_mask: jax.Array,
        *,
        h0: float,
        omega_gw_min: float | None = None,
    ) -> Figure:
        """Plot $\\Omega_{\\mathrm{GW}}(f)$ and $S_h(f)$ on dual $y$-axes.

        ``omega_gw_min`` defaults to ``None``, which leaves both axes autoscaled.
        """
        freq, omega, sh, _ = band_limited_spectrum(
            frequencies,
            spectral_density_arr,
            frequency_mask,
            h0=h0,
        )
        _fig, ax_sh = plt.subplots()
        draw_omega_and_sh(
            ax_sh,
            freq,
            omega,
            sh,
            omega_gw_min=omega_gw_min,
        )
        return _fig

    return (plot_omega_and_sh,)


@app.cell
def _(
    BASE_DIR,
    FIDUCIALS,
    OMEGA_GW_MIN,
    ROOT_DIR,
    frequencies,
    frequency_mask,
    plot_omega_and_sh,
    save_figures,
    spectral_density,
):
    _fig = plot_omega_and_sh(
        frequencies,
        spectral_density,
        frequency_mask,
        h0=FIDUCIALS["H0"],
        omega_gw_min=OMEGA_GW_MIN,
    )
    save_figures({BASE_DIR / "omega_and_sh.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Network effective PSDs
    """)
    return


@app.cell
def _(
    DETECTOR_COMPARISON_LEGEND,
    Figure,
    Mapping,
    Network,
    Sequence,
    format_axis_ticks,
    jax,
    network_legend_handles,
    np,
    plt,
):
    def plot_effective_psds(
        frequencies: jax.Array,
        networks: Sequence[Network],
        psds_by_network: Mapping[str, jax.Array | np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
        frequency_mask: jax.Array,
    ) -> Figure:
        """Overlay network effective PSDs on shared log–log axes."""
        if len(networks) != len(colors) or len(networks) != len(linestyles):
            raise ValueError("color and linestyle counts must match the networks")

        _fig, ax = plt.subplots()
        mask = np.asarray(frequency_mask)
        freq = np.asarray(frequencies)[mask]
        for network, color, linestyle in zip(networks, colors, linestyles, strict=True):
            psd = np.asarray(psds_by_network[network.name])[mask]
            pos = np.isfinite(psd) & (psd > 0.0) & (freq > 0.0)
            ax.loglog(
                freq[pos],
                psd[pos],
                color=color,
                linestyle=linestyle,
            )

        ax.set_xlabel(r"$f\ \mathrm{(Hz)}$")
        ax.set_ylabel(r"$S_{\mathrm{eff}}(f)\ \mathrm{[Hz^{-1}]}$")
        ax.set_axisbelow(True)
        ax.grid(True, which="both", linestyle=":", linewidth=0.5, alpha=0.5)
        format_axis_ticks(ax)
        ax.legend(
            handles=network_legend_handles(networks, colors, linestyles),
            **DETECTOR_COMPARISON_LEGEND,
        )
        _fig.tight_layout()
        return _fig

    return (plot_effective_psds,)


@app.cell
def _(
    BASE_DIR,
    NETWORKS,
    ROOT_DIR,
    detector_colors,
    detector_linestyles,
    effective_psds,
    frequencies,
    frequency_mask,
    plot_effective_psds,
    save_figures,
):
    _fig = plot_effective_psds(
        frequencies,
        NETWORKS,
        effective_psds,
        colors=detector_colors,
        linestyles=detector_linestyles,
        frequency_mask=frequency_mask,
    )
    save_figures({BASE_DIR / "effective_psds.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## $S_h$ versus network sensitivity curves
    """)
    return


@app.cell
def _(
    DETECTOR_COMPARISON_LEGEND,
    Figure,
    Mapping,
    Network,
    Sequence,
    format_axis_ticks,
    network_legend_handles,
    np,
    plt,
):
    def plot_spectrum_and_sensitivities(
        frequency: np.ndarray,
        spectrum: np.ndarray,
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        sensitivities_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
        spectrum_label: str,
        spectrum_color: str,
        spectrum_linestyle: str,
        ylabel: str,
        ymin: float | None = None,
        include_spectrum_in_legend: bool = True,
        spectrum_legend_loc: str | None = None,
    ) -> Figure:
        """Overlay a fiducial spectrum with per-network Gaussian sensitivities.

        When ``spectrum_legend_loc`` is set, the spectrum gets its own legend inside
        the axes (e.g. ``"upper left"``). The network legend still uses
        ``DETECTOR_COMPARISON_LEGEND`` above the frame and remains ``ax.legend_``
        so ``tight_layout`` keeps reserving space for it; the inner legend is
        pinned with ``ax.add_artist``.
        """
        if len(networks) != len(colors) or len(networks) != len(linestyles):
            raise ValueError("color and linestyle counts must match the networks")
        if include_spectrum_in_legend and spectrum_legend_loc is not None:
            raise ValueError(
                "use at most one of include_spectrum_in_legend and spectrum_legend_loc"
            )

        _fig, ax = plt.subplots()
        (line_spectrum,) = ax.loglog(
            frequency,
            spectrum,
            color=spectrum_color,
            linestyle=spectrum_linestyle,
            label=spectrum_label,
        )
        for network, color, linestyle in zip(networks, colors, linestyles, strict=True):
            network_frequency = np.asarray(frequency_by_network[network.name])
            sensitivity = np.asarray(sensitivities_by_network[network.name])
            pos = (
                np.isfinite(sensitivity)
                & (sensitivity > 0.0)
                & (network_frequency > 0.0)
            )
            ax.loglog(
                network_frequency[pos],
                sensitivity[pos],
                color=color,
                linestyle=linestyle,
            )

        ax.set_xlabel(r"$f\ \mathrm{(Hz)}$")
        ax.set_ylabel(ylabel)
        if ymin is not None:
            _, ymax = ax.get_ylim()
            ax.set_ylim(ymin, ymax)
        ax.set_axisbelow(True)
        ax.grid(True, which="both", linestyle=":", linewidth=0.5, alpha=0.5)
        format_axis_ticks(ax)
        network_handles = network_legend_handles(networks, colors, linestyles)
        legend_handles = (
            [line_spectrum, *network_handles]
            if include_spectrum_in_legend
            else network_handles
        )
        if spectrum_legend_loc is not None:
            # Keep the detector legend as ax.legend_ so tight_layout still
            # accounts for the above-axes bbox; pin the spectrum entry separately.
            spectrum_legend = ax.legend(
                handles=[line_spectrum],
                loc=spectrum_legend_loc,
                frameon=False,
                handlelength=2.5,
            )
            ax.add_artist(spectrum_legend)
        ax.legend(handles=legend_handles, **DETECTOR_COMPARISON_LEGEND)
        _fig.tight_layout()
        return _fig

    return (plot_spectrum_and_sensitivities,)


@app.cell
def _(
    BASE_DIR,
    NETWORKS,
    OMEGA_GW_MIN,
    ROOT_DIR,
    SPECTRUM,
    SPECTRUM_LINESTYLES,
    detector_colors,
    detector_linestyles,
    fiducial_freq,
    fiducial_omega,
    fiducial_sh,
    frequency_by_network,
    plot_spectrum_and_sensitivities,
    save_figures,
    sh_ymin_matching_omega_floor,
    sigma_by_network,
):
    _fig = plot_spectrum_and_sensitivities(
        fiducial_freq,
        fiducial_sh,
        NETWORKS,
        frequency_by_network,
        sigma_by_network,
        colors=detector_colors,
        linestyles=detector_linestyles,
        spectrum_label=r"$S_h$",
        spectrum_color=SPECTRUM["sh"],
        spectrum_linestyle=SPECTRUM_LINESTYLES["sh"],
        ylabel=r"$S_h(f), \, \sigma(f)\ \mathrm{[Hz^{-1}]}$",
        ymin=sh_ymin_matching_omega_floor(fiducial_omega, fiducial_sh, OMEGA_GW_MIN),
        include_spectrum_in_legend=False,
        spectrum_legend_loc="upper left",
    )
    save_figures({BASE_DIR / "sh_and_sigma.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## $\Omega_{\mathrm{GW}}$ and network sensitivity curves
    """)
    return


@app.cell
def _(
    BASE_DIR,
    NETWORKS,
    OMEGA_GW_MIN,
    ROOT_DIR,
    SPECTRUM,
    detector_colors,
    detector_linestyles,
    fiducial_freq,
    fiducial_omega,
    frequency_by_network,
    omega_sigma_by_network,
    plot_spectrum_and_sensitivities,
    save_figures,
):
    _fig = plot_spectrum_and_sensitivities(
        fiducial_freq,
        fiducial_omega,
        NETWORKS,
        frequency_by_network,
        omega_sigma_by_network,
        colors=detector_colors,
        linestyles=detector_linestyles,
        spectrum_label=r"$\Omega_{\mathrm{GW}}$",
        spectrum_color=SPECTRUM["omega_gw"],
        spectrum_linestyle=":",
        ylabel=r"$\Omega_{\mathrm{GW}}(f), \, \sigma(f)$",
        ymin=OMEGA_GW_MIN,
        include_spectrum_in_legend=False,
        spectrum_legend_loc="upper left",
    )
    save_figures({BASE_DIR / "omega_and_sigma.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Inspecting the SNR of the spectral density
    """)
    return


@app.cell
def _(
    DETECTOR_COMPARISON_LEGEND,
    Figure,
    Mapping,
    MplAxes,
    Network,
    Sequence,
    format_axis_ticks,
    network_legend_handles,
    np,
    plt,
):
    def _draw_snr_curves(
        ax: MplAxes,
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        values_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
        ylabel: str,
        loglog: bool = False,
    ) -> None:
        """Overlay one per-network SNR curve on ``ax`` and style the axes."""
        if len(networks) != len(colors) or len(networks) != len(linestyles):
            raise ValueError("color and linestyle counts must match the networks")

        draw = ax.loglog if loglog else ax.semilogx
        for network, color, linestyle in zip(networks, colors, linestyles, strict=True):
            draw(
                frequency_by_network[network.name],
                values_by_network[network.name],
                color=color,
                linestyle=linestyle,
            )

        ax.set_xlabel(r"$f\ \mathrm{(Hz)}$")
        ax.set_ylabel(ylabel)
        ax.set_axisbelow(True)
        ax.grid(True, which="both", linestyle=":", linewidth=0.5, alpha=0.5)
        format_axis_ticks(ax)
        ax.legend(
            handles=network_legend_handles(networks, colors, linestyles),
            **DETECTOR_COMPARISON_LEGEND,
        )

    def plot_snr_integrand(
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        snr_squared_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
    ) -> Figure:
        """Plot the per-network matched-filter integrand."""
        _fig, ax = plt.subplots()
        _draw_snr_curves(
            ax,
            networks,
            frequency_by_network,
            snr_squared_by_network,
            colors=colors,
            linestyles=linestyles,
            ylabel=r"$\Delta\mathrm{SNR}^{2}(f)$",
            loglog=True,
        )
        _fig.tight_layout()
        return _fig

    def plot_snr_cumulative_below(
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        snr_lt_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
    ) -> Figure:
        """Plot each network's SNR accumulated from the low-frequency end."""
        _fig, ax = plt.subplots()
        _draw_snr_curves(
            ax,
            networks,
            frequency_by_network,
            snr_lt_by_network,
            colors=colors,
            linestyles=linestyles,
            ylabel=r"$\mathrm{SNR}(<f) / \mathrm{SNR}_{\mathrm{tot}}$",
        )
        _fig.tight_layout()
        return _fig

    def plot_snr_cumulative_above(
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        snr_gt_by_network: Mapping[str, np.ndarray],
        *,
        colors: Sequence[str],
        linestyles: Sequence[str],
    ) -> Figure:
        """Plot each network's SNR accumulated from the high-frequency end."""
        _fig, ax = plt.subplots()
        _draw_snr_curves(
            ax,
            networks,
            frequency_by_network,
            snr_gt_by_network,
            colors=colors,
            linestyles=linestyles,
            ylabel=r"$\mathrm{SNR}(>f) / \mathrm{SNR}_{\mathrm{tot}}$",
        )
        _fig.tight_layout()
        return _fig

    return (
        plot_snr_cumulative_above,
        plot_snr_cumulative_below,
        plot_snr_integrand,
    )


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Plotting the SNR accumulated in each frequency bin
    """)
    return


@app.cell
def _(
    BASE_DIR,
    NETWORKS,
    ROOT_DIR,
    detector_colors,
    detector_linestyles,
    frequency_by_network,
    plot_snr_integrand,
    save_figures,
    snr_squared_by_network,
):
    _fig = plot_snr_integrand(
        NETWORKS,
        frequency_by_network,
        snr_squared_by_network,
        colors=detector_colors,
        linestyles=detector_linestyles,
    )
    save_figures({BASE_DIR / "snr_integrand.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Plotting the fraction of SNR below a given frequency
    """)
    return


@app.cell
def _(
    BASE_DIR,
    NETWORKS,
    ROOT_DIR,
    detector_colors,
    detector_linestyles,
    frequency_by_network,
    plot_snr_cumulative_below,
    save_figures,
    snr_lt_by_network,
):
    _fig = plot_snr_cumulative_below(
        NETWORKS,
        frequency_by_network,
        snr_lt_by_network,
        colors=detector_colors,
        linestyles=detector_linestyles,
    )
    save_figures({BASE_DIR / "snr_cumulative_below.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ### Plotting the fraction of SNR above a given frequency
    """)
    return


@app.cell
def _(
    BASE_DIR,
    NETWORKS,
    ROOT_DIR,
    detector_colors,
    detector_linestyles,
    frequency_by_network,
    plot_snr_cumulative_above,
    save_figures,
    snr_gt_by_network,
):
    _fig = plot_snr_cumulative_above(
        NETWORKS,
        frequency_by_network,
        snr_gt_by_network,
        colors=detector_colors,
        linestyles=detector_linestyles,
    )
    save_figures({BASE_DIR / "snr_cumulative_above.pdf": _fig}, root=ROOT_DIR)
    _fig
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Dependence of the SNR on the low-frequency cutoff $f_\mathrm{min}$

    Absolute $\mathrm{SNR}(>f)$ at $f = 2, 5, 10, 20\ \mathrm{Hz}$ for each
    detector network. Values come from the same right-cumulative sum as the
    normalized curves above, evaluated at the band bin nearest each cutoff.
    """)
    return


@app.cell
def _(Mapping, Network, Sequence, cumulative_snr_above_at, np, pd):
    def build_cumulative_snr_above_table(
        networks: Sequence[Network],
        frequency_by_network: Mapping[str, np.ndarray],
        snr_squared_by_network: Mapping[str, np.ndarray],
        f_cutoffs_hz: Sequence[float],
    ) -> tuple[pd.DataFrame, str]:
        """Tabulate absolute SNR(>f) at each cutoff for every network."""
        rows: list[dict[str, float | str]] = []
        for network in networks:
            frequency = frequency_by_network[network.name]
            snr_squared = snr_squared_by_network[network.name]
            row: dict[str, float | str] = {
                "Detector Network": rf"{network.label}",
            }
            for f_cutoff in f_cutoffs_hz:
                row[f"SNR above {f_cutoff:g} Hz"] = cumulative_snr_above_at(
                    frequency,
                    snr_squared,
                    f_cutoff,
                )
            rows.append(row)

        df = pd.DataFrame(rows)
        df.set_index("Detector Network", inplace=True)
        latex_table = df.to_latex(
            index=True,
            escape=False,
            float_format="%.2g",
            caption=(
                "Matched-filter SNR accumulated above $f$ for each detector network "
                "at the fiducial injection."
            ),
            label="tab:fiducial_cumulative_snr_above",
        )
        return df, latex_table

    return (build_cumulative_snr_above_table,)


@app.cell
def _(
    CUMULATIVE_SNR_ABOVE_FMINS_HZ,
    NETWORKS,
    build_cumulative_snr_above_table,
    frequency_by_network,
    snr_squared_by_network,
):
    cumulative_snr_above_table, latex_table = build_cumulative_snr_above_table(
        NETWORKS,
        frequency_by_network,
        snr_squared_by_network,
        CUMULATIVE_SNR_ABOVE_FMINS_HZ,
    )
    cumulative_snr_above_table
    return cumulative_snr_above_table, latex_table


@app.cell
def _(BASE_DIR, latex_table):
    BASE_DIR.mkdir(parents=True, exist_ok=True)
    _cumulative_snr_above_tex_path = BASE_DIR / "cumulative_snr_above.tex"
    _cumulative_snr_above_tex_path.write_text(
        latex_table,
        encoding="utf-8",
    )
    print("saved:", _cumulative_snr_above_tex_path)
    return


if __name__ == "__main__":
    app.run()
