"""Headless, config-driven NumPyro MCMC runner for the astrophysical GWB.

This is the SLURM-friendly port of ``notebooks/mcmc.py``: it importance-reweights a
fixed polarization-power catalog through NUTS to infer cosmological / population
hyperparameters, reading every setting from a TOML or JSON config file and emitting
only ``logging`` progress (no plots). It saves an ArviZ ``InferenceData`` NetCDF
and, beside it, the defaults-filled config that produced it -- so the chain and
the record of its settings travel together.

Design constraint (do not "tidy" away): config parsing lives in
``astrogwb.paper.config.mcmc``, which imports only stdlib + pydantic at module
load and materializes priors without evaluating any JAX op ("is the backend
still uninitialized?" is guarded by a subprocess test). ``OMP_NUM_THREADS`` /
``XLA_FLAGS`` and ``numpyro.set_host_device_count(...)`` must be set *before* JAX
initializes its backend, so backend-claiming work happens only after
:func:`astrogwb.paper.runtime.configure_runtime`. The pre-flight catalog import
may load JAX, but is kept free of array creation and device queries; a subprocess
test guards that distinction. See the runtime helper for the ordering.

Usage -- one flag per config block, each already merged across the layers
that declare it::

    RUN=config/runs/cosmological-parameters/ET-2L-aligned-CE-Hanford.json
    BASE=config/runs/cosmological-parameters/_base.json
    LAYERS="config/analysis.json config/fiducials.json config/networks.json \
        config/priors.json config/sampler.json $BASE $RUN"
    uv run --extra paper python scripts/run_mcmc.py \
        --analysis "$(jq -s 'map(.analysis // {}) | reduce .[] as $b ({}; . * $b)' $LAYERS)" \
        --fiducials "$(jq -s 'map(.fiducials // {}) | reduce .[] as $b ({}; . * $b)' $LAYERS)" \
        --networks "$(jq -s 'map(.networks // {}) | reduce .[] as $b ({}; . * $b)' $LAYERS)" \
        --priors "$(jq -s 'map(.priors // {}) | reduce .[] as $b ({}; . + $b)' $LAYERS)" \
        --sampler "$(jq -s 'map(.sampler // {}) | reduce .[] as $b ({}; . * $b)' $LAYERS)" \
        --injection-catalog outputs/catalogs/md-imrphenom-s41-n32768.h5 \
        --proposal-catalog outputs/catalogs/md-imrphenom-s42-n16384.h5

One operator per block is the whole merge rule: ``*`` (deep) everywhere, and
``+`` (shallow) for ``priors``, so an overridden ``[priors.<param>]`` table
replaces the inherited one rather than key-merging a normal prior onto a
uniform one and leaving stale ``low`` / ``high`` behind. The ``run_mcmc``
workflow rule declares the same layer files as ``input:`` and folds them
exactly this way; ``tests/paper/test_runs.py`` pins the folds against
``merge_config_layers``, which is the Python path the notebooks and the
validation gate take.

Taking blocks rather than paths is why merge order is no longer this script's
concern: each block arrives folded, so there is no order left to get wrong and
nothing to log. The resolved config still lands beside the chain.

The run config's ``[analysis.catalog]`` block names one per role; the two files
are supplied directly as ``--injection-catalog`` and ``--proposal-catalog``.
Roles are fixed, so no name-to-path mapping is needed.

The importance-sampling *proposal density* is not in the config and is not
derived here either: the proposal catalog records its own population model,
that model's construction settings, and the hyperparameters it was drawn at, so
the weights are divided by what was actually generated by construction rather
than by agreement. There is nothing left to cross-check against the run's
fiducials. The recorded population, narrowed to the run's analysis redshift
window, is stamped into the saved chain, which stays the self-describing record
of what was sampled.

See docs/running-inference.md for the layer tree, and
``scripts/validate_configs.py`` for the pre-flight gate over every run.

Add ``--extra cuda`` (or ``--extra tpu``) to ``uv run`` for the matching JAX
accelerator plugin.
Batch runs are dispatched by the Snakemake ``run_mcmc`` rule (one config per
job); see the paper project's ``Snakefile`` and SLURM profiles.
"""

from __future__ import annotations

import argparse
import logging
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from astrogwb.paper.config.catalogs import check_catalog_references
from astrogwb.paper.config.mcmc import RunConfig, build_run_config
from astrogwb.paper.config.runs import add_block_arguments, load_config_blocks
from astrogwb.paper.runtime import add_runtime_arguments, configure_runtime

if TYPE_CHECKING:
    from astrogwb.catalog import PolarizationPowerCatalog
    from astrogwb.paper.inference import AmplitudeMarginalization

logger = logging.getLogger("run_mcmc")


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Headless NumPyro MCMC runner for the astrophysical GWB. Reads all "
            "settings from a TOML or JSON config; saves an ArviZ NetCDF."
        )
    )
    add_block_arguments(parser)
    parser.add_argument(
        "--injection-catalog",
        type=Path,
        required=True,
        metavar="PATH",
        help="The catalog file this run's [analysis.catalog].injection names.",
    )
    parser.add_argument(
        "--proposal-catalog",
        type=Path,
        required=True,
        metavar="PATH",
        help="The catalog file this run's [analysis.catalog].proposal names.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Override the config seed (handy for array sweeps).",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        default=None,
        help="Override the config [output] outdir.",
    )
    parser.add_argument(
        "--label",
        type=str,
        default=None,
        help="Override the config [output] label.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Log at WARNING instead of INFO.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace an existing NetCDF chain for this run.",
    )
    add_runtime_arguments(parser)
    return parser.parse_args(argv)


# --------------------------------------------------------------------------- #
# Inference
# --------------------------------------------------------------------------- #
def run(
    config: RunConfig,
    injection_catalog: PolarizationPowerCatalog,
    proposal_catalog: PolarizationPowerCatalog,
    jax,
    chain_method: str,
):
    """Replicate the notebook inference cells headlessly and return the MCMC object.

    Returns ``(mcmc, marginalization, inputs)``, where ``marginalization`` is
    the :class:`~astrogwb.paper.inference.AmplitudeMarginalization` built for an
    amplitude-marginalized run, or ``None`` for the default likelihood.
    """
    from numpyro.infer import MCMC, NUTS
    from numpyro.infer.initialization import init_to_value

    from astrogwb.paper.inference import (
        build_model,
        initial_values,
        prepare_inference_inputs,
        target_population,
    )

    inputs = prepare_inference_inputs(
        injection_catalog,
        proposal_catalog,
        grid=config.analysis.grid,
        detectors=config.analysis.detectors,
        target=target_population(config),
        density_sites=config.analysis.population.density_sites,
    )
    model, marginalization = build_model(
        config,
        spectral_density_fn=inputs.spectral_density_fn,
    )

    sampler = config.sampler
    init_strategy = init_to_value(values=initial_values(config))
    kernel = NUTS(
        model,
        target_accept_prob=sampler.target_accept,
        adapt_step_size=True,
        adapt_mass_matrix=True,
        forward_mode_differentiation=sampler.forward_mode_differentiation,
        dense_mass=sampler.dense_mass,
        max_tree_depth=sampler.max_tree_depth,
        init_strategy=init_strategy,
    )
    mcmc = MCMC(
        kernel,
        num_warmup=sampler.num_warmup,
        num_samples=sampler.num_samples,
        num_chains=sampler.num_chains,
        chain_method=chain_method,
        progress_bar=sampler.progress_bar,
        jit_model_args=sampler.jit_model_args,
    )

    logger.info(
        "Sampling: warmup=%d samples=%d chains=%d target_accept=%.3f forward_mode=%s",
        sampler.num_warmup,
        sampler.num_samples,
        sampler.num_chains,
        sampler.target_accept,
        sampler.forward_mode_differentiation,
    )
    rng_key = jax.random.PRNGKey(config.sampler.seed)
    mcmc.run(
        rng_key,
        **inputs.model_kwargs(),
        extra_fields=("num_steps", "accept_prob", "diverging"),
    )

    # numpyro prints the summary to stdout; route it through logging for SLURM logs.
    logger.info("Sampling complete; summary follows")
    mcmc.print_summary()
    return mcmc, marginalization, inputs


def chain_output_path(config: RunConfig, *, timestamp: str | None = None) -> Path:
    """Return the NetCDF chain path a run will write.

    Campaign configs always have a label.  Auto-labelled ad-hoc runs retain the
    timestamped naming convention, while still allowing a collision check before
    expensive sampling starts.
    """
    if config.output.label:
        base = config.output.label
    else:
        timestamp = timestamp or datetime.now().astimezone().strftime("%Y%m%d-%H%M%S")
        params_suffix = "-".join(config.analysis.sampled_params)
        det_suffix = ",".join(config.analysis.detectors)
        base = f"mcmc-{params_suffix}-det={det_suffix}-seed{config.sampler.seed}-{timestamp}"
    return config.output.outdir / f"{base}.nc"


def ensure_chain_path_available(
    config: RunConfig, *, timestamp: str | None = None, force: bool = False
) -> Path:
    """Fail before sampling if the chain already exists."""
    nc_path = chain_output_path(config, timestamp=timestamp)
    if nc_path.exists() and not force:
        raise FileExistsError(
            f"refusing to replace existing MCMC output: {nc_path}. "
            "Pass --force only for an intentional replacement."
        )
    return nc_path


def save(
    mcmc,
    config: RunConfig,
    *,
    proposal: PolarizationPowerCatalog | None = None,
    timestamp: str | None = None,
    force: bool = False,
    marginalization: AmplitudeMarginalization | None = None,
) -> Path:
    """Write the ArviZ NetCDF chain and its config record, and log IS health.

    The resolved, defaults-filled config lands beside the chain, so two runs
    that reach the same settings by different overrides produce identical
    records. There is no layer list to stamp: this script is handed blocks,
    already folded, rather than an ordered list of files.
    """
    import json
    from functools import partial

    import arviz as az
    import numpy as np
    import xarray as xr

    config.output.outdir.mkdir(parents=True, exist_ok=True)
    timestamp = timestamp or datetime.now().astimezone().strftime("%Y%m%d-%H%M%S")
    nc_path = ensure_chain_path_available(config, timestamp=timestamp, force=force)

    idata = az.from_numpyro(mcmc)

    # The proposal density lives in the catalog file, not in the config, so the
    # assembled JSON config does not carry it. Stamping the catalog's own
    # population record -- narrowed to this run's analysis window -- keeps the
    # chain the complete, self-describing record of what was sampled.
    if proposal is not None:
        idata.posterior.attrs["proposal"] = json.dumps(
            {
                # The record itself, not a field-by-field restatement of it:
                # one spelling, so a field added to PopulationMetadata reaches
                # the chain without an edit here.
                "population": proposal.population.model_dump(mode="json"),
                "params": dict(proposal.fiducials),
                "num_samples": proposal.num_samples,
            },
            sort_keys=True,
        )

    if marginalization is not None:
        import jax
        from numpyro.infer import Predictive

        from astrogwb.sampling.models import amplitude_reconstruction_model

        amplitude_parameter = marginalization.parameter

        # Reconstruction runs here, in-process, against the very objects the
        # chain was marginalized with -- which is why nothing about the
        # quadrature needs persisting to the NetCDF.
        # The sufficient statistics form the AmplitudeConditional batch shape;
        # one Predictive invocation draws one amplitude per (chain, draw).
        posterior_samples = mcmc.get_samples(group_by_chain=True)
        draws = Predictive(
            partial(
                amplitude_reconstruction_model,
                amplitude_parameter=amplitude_parameter,
                amplitude_fn=marginalization.amplitude_fn,
                merger_rate_amplitude_fn=marginalization.merger_rate_fn,
                prior=marginalization.prior,
                fiducial=marginalization.fiducial,
                grid=marginalization.grid,
            ),
            num_samples=1,
            return_sites=[
                amplitude_parameter,
                "total_merger_rate",
                "quadrature_effective_nodes",
            ],
        )(
            jax.random.fold_in(jax.random.PRNGKey(config.sampler.seed), 1),
            amplitude_mle=posterior_samples["amplitude_mle"],
            template_optimal_snr=posterior_samples["template_optimal_snr"],
            template_merger_rate=posterior_samples["template_merger_rate"],
        )
        draws = {name: values[0] for name, values in draws.items()}

        # `az.from_numpyro` returns an xarray DataTree, whose __setitem__ does
        # not accept a Dataset-style `(dims, values)` tuple: it would store the
        # tuple as an object scalar and fail at `to_netcdf`. Assign DataArrays.
        for name, values in draws.items():
            idata.posterior[name] = xr.DataArray(
                np.asarray(values), dims=("chain", "draw")
            )

        effective_nodes = draws["quadrature_effective_nodes"]

        min_effective_nodes = float(np.min(effective_nodes))
        if min_effective_nodes < 30:
            logger.warning(
                "quadrature_effective_nodes min=%.1f is below 30; the amplitude "
                "grid may not resolve the conditional posterior. Consider "
                "raising analysis.amplitude_num_nodes.",
                min_effective_nodes,
            )

    idata.to_netcdf(nc_path)

    # The record of the run's settings, beside the chain rather than in a
    # parallel tree linked only by filename convention. `save` writes the
    # defaults-filled RunConfig, so two runs that reach the same settings
    # by different layer overrides produce identical files.
    config_record = nc_path.with_suffix(".json")
    config.save(config_record)
    logger.info("Saved %s", config_record)

    # Importance-sampling health: relative ESS near 1 means the proposal catalog
    # still reweights well at the posterior.
    post = idata.posterior
    ress = post["importance_relative_ess"].values.ravel()
    rate = post["total_merger_rate"].values.ravel()
    logger.info("importance_relative_ess: mean=%.3f min=%.3f", ress.mean(), ress.min())
    logger.info("total_merger_rate [/s]: mean=%.4e", rate.mean())
    logger.info("Saved %s", nc_path)
    return nc_path


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    logging.basicConfig(
        level=logging.WARNING if args.quiet else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )

    config = build_run_config(
        load_config_blocks(args),
        seed=args.seed,
        outdir=args.outdir.resolve() if args.outdir else None,
        label=args.label,
    )
    # The pre-flight check `assemble_config` used to run once per run on the
    # way to every chain: reject an unknown catalog before JAX claims a
    # device. `scripts/validate_configs.py` runs it over all runs at once,
    # before any catalog is built.
    check_catalog_references(config, label=args.label or "run")

    logger.info(
        "Sampling %s | fixed %s",
        tuple(config.analysis.sampled_params),
        tuple(config.fixed_params),
    )

    # Pick a single timestamp now and check the artifact before JAX starts.
    # Labelled experiment runs are deterministic; auto-labelled runs preserve the
    # existing timestamp convention.
    timestamp = datetime.now().astimezone().strftime("%Y%m%d-%H%M%S")
    ensure_chain_path_available(config, timestamp=timestamp, force=args.force)

    from astrogwb.paper.catalogs import load_run_catalog

    # Load both catalogs before JAX claims a device. Loading validates each
    # file's population record against its own arrays, so a missing file, a
    # catalog whose columns drifted from its declared population, or a model
    # that no longer reproduces the density it was drawn from all fail cheaply.
    injection_path = args.injection_catalog.resolve()
    proposal_path = args.proposal_catalog.resolve()
    injection_catalog = load_run_catalog(injection_path, label="injection")
    proposal_catalog = load_run_catalog(proposal_path, label="proposal")
    logger.info(
        "Proposal density from %s: model=%s kwargs=%s params=%s",
        config.analysis.catalog.proposal,
        proposal_catalog.population_model_name,
        dict(proposal_catalog.population_model_kwargs),
        dict(proposal_catalog.fiducials),
    )

    jax, chain_method = configure_runtime(
        num_chains=config.sampler.num_chains,
        platform=args.platform,
        host_device_count=args.host_device_count,
        cpu_threads=args.cpu_threads,
        chain_method=args.chain_method,
    )
    mcmc, marginalization, inputs = run(
        config,
        injection_catalog,
        proposal_catalog,
        jax,
        chain_method,
    )
    save(
        mcmc,
        config,
        proposal=inputs.proposal,
        timestamp=timestamp,
        force=args.force,
        marginalization=marginalization,
    )


if __name__ == "__main__":
    main()
