"""Typed source, production-population, and waveform-catalog recipes."""

from __future__ import annotations

import math
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, cast, get_args

from astrogwb_paper.config.loading import deep_merge, load_inventory
from astrogwb_paper.paths import paper_project_root

CATALOGS_PATH = Path("inputs/catalogs.yaml")
INJECTION_CATALOG_NAME = "injection-bns-n32768"
_INVENTORY_SECTIONS = ("base", "sources", "injection", "catalogs")
AssemblyOperation = Literal["identity", "subsample", "mixture"]
ASSEMBLY_OPERATIONS: tuple[AssemblyOperation, ...] = get_args(AssemblyOperation)
"""Runtime view of :data:`AssemblyOperation`, for argparse choices and checks.

Derived from the type rather than restated, so the CLI, the recipe validator,
and the assembly dispatch can never disagree about the supported operations.
"""


@dataclass(frozen=True)
class SourcePopulationRecipe:
    """One finite population pool generated directly by ``gwmock-pop``."""

    name: str
    population_config: Path
    num_samples: int
    seed: int


@dataclass(frozen=True)
class AssemblyComponent:
    """One weighted source pool used to assemble a production population."""

    source: str
    weight: float


@dataclass(frozen=True)
class ProductionPopulationRecipe:
    """A production population assembled from one or more source pools."""

    operation: AssemblyOperation
    num_samples: int
    seed: int
    components: tuple[AssemblyComponent, ...]
    uniform_redshift_fraction: float | None = None


@dataclass(frozen=True)
class WaveformRecipe:
    """Waveform settings shared by injection and proposal production populations."""

    approximant: str
    sampling_frequency: float
    minimum_frequency: float
    maximum_frequency: float
    reference_frequency: float
    frequency_resolution: float
    chunk_size: int


@dataclass(frozen=True)
class CatalogRecipe:
    """One production population and the waveform catalog generated from it."""

    name: str
    production: ProductionPopulationRecipe
    waveform: WaveformRecipe


@dataclass(frozen=True)
class CatalogInventory:
    """Complete catalog DAG declared by the committed inventory."""

    sources: dict[str, SourcePopulationRecipe]
    injection: CatalogRecipe
    catalogs: dict[str, CatalogRecipe]


def inventory_path(root: Path | None = None) -> Path:
    """Return the committed catalog recipe inventory path."""
    return (root or paper_project_root()) / CATALOGS_PATH


def load_catalog_inventory(path: Path | None = None) -> CatalogInventory:
    """Load and cross-validate the complete committed catalog DAG."""
    resolved = path or inventory_path()
    raw = load_inventory(resolved, required=_INVENTORY_SECTIONS)
    base = raw["base"]
    sources_raw = raw["sources"]
    injection_raw = raw["injection"]
    catalogs_raw = raw["catalogs"]
    assert isinstance(base, Mapping)
    assert isinstance(sources_raw, Mapping)
    assert isinstance(injection_raw, Mapping)
    assert isinstance(catalogs_raw, Mapping)

    sources = {
        _require_name(name, resolved, "source"): _source_from_mapping(
            str(name), value, resolved
        )
        for name, value in sources_raw.items()
    }
    injection = _catalog_from_mapping(
        "injection",
        deep_merge(base, injection_raw),
        sources=sources,
        path=resolved,
        allow_proposal_density=False,
    )
    catalogs: dict[str, CatalogRecipe] = {}
    for name, overlay in catalogs_raw.items():
        catalog_name = _require_name(name, resolved, "catalog")
        if overlay is not None and not isinstance(overlay, Mapping):
            raise TypeError(f"{resolved} catalog {catalog_name!r} must be a mapping")
        catalogs[catalog_name] = _catalog_from_mapping(
            catalog_name,
            deep_merge(base, overlay or {}),
            sources=sources,
            path=resolved,
            allow_proposal_density=True,
        )
    return CatalogInventory(sources=sources, injection=injection, catalogs=catalogs)


def load_sources(path: Path | None = None) -> dict[str, SourcePopulationRecipe]:
    """Load the named source pools generated by ``gwmock-pop``."""
    return load_catalog_inventory(path).sources


def injection_recipe(path: Path | None = None) -> CatalogRecipe:
    """Load the shared independent injection recipe."""
    return load_catalog_inventory(path).injection


def load_catalogs(path: Path | None = None) -> dict[str, CatalogRecipe]:
    """Load every named proposal waveform-catalog recipe."""
    return load_catalog_inventory(path).catalogs


def catalog_recipe(name: str) -> CatalogRecipe:
    """Return a named proposal recipe or raise a user-facing error."""
    catalogs = load_catalogs()
    try:
        return catalogs[name]
    except KeyError:
        choices = ", ".join(catalogs)
        raise ValueError(f"unknown catalog {name!r}; choose from {choices}") from None


def _require_name(name: object, path: Path, kind: str) -> str:
    if not isinstance(name, str) or not name:
        raise ValueError(f"{path} has an invalid {kind} name")
    return name


def _require_operation(value: object, name: str) -> AssemblyOperation:
    """Narrow a raw recipe value to a supported assembly operation."""
    if value not in ASSEMBLY_OPERATIONS:
        raise ValueError(f"{name} has unsupported production operation {value!r}")
    return cast(AssemblyOperation, value)


def _require_mapping(value: object, *, label: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise TypeError(f"{label} must be a mapping")
    return value


def _source_from_mapping(name: str, raw: object, path: Path) -> SourcePopulationRecipe:
    mapping = _require_mapping(raw, label=f"{path} source {name!r}")
    try:
        recipe = SourcePopulationRecipe(
            name=name,
            population_config=Path(mapping["config"]),
            num_samples=int(mapping["num_samples"]),
            seed=int(mapping["seed"]),
        )
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError(f"invalid source recipe {name!r}") from exc
    if recipe.num_samples <= 0:
        raise ValueError(f"source recipe {name!r} num_samples must be > 0")
    return recipe


def _catalog_from_mapping(
    name: str,
    raw: Mapping[str, Any],
    *,
    sources: Mapping[str, SourcePopulationRecipe],
    path: Path,
    allow_proposal_density: bool,
) -> CatalogRecipe:
    try:
        production = _production_from_mapping(
            name,
            _require_mapping(raw["production"], label=f"{name}.production"),
            sources=sources,
            allow_proposal_density=allow_proposal_density,
        )
        waveform = _waveform_from_mapping(
            _require_mapping(raw["waveform"], label=f"{name}.waveform")
        )
    except (KeyError, TypeError, ValueError) as exc:
        if isinstance(exc, ValueError) and str(exc).startswith(name):
            raise
        raise ValueError(f"invalid catalog recipe {name!r} in {path}") from exc
    return CatalogRecipe(name=name, production=production, waveform=waveform)


def _production_from_mapping(
    name: str,
    raw: Mapping[str, Any],
    *,
    sources: Mapping[str, SourcePopulationRecipe],
    allow_proposal_density: bool,
) -> ProductionPopulationRecipe:
    operation = _require_operation(raw["operation"], name)
    components_raw = raw["components"]
    if not isinstance(components_raw, list) or not components_raw:
        raise ValueError(f"{name} production components must be a non-empty list")
    components: list[AssemblyComponent] = []
    for component_raw in components_raw:
        component = _require_mapping(
            component_raw, label=f"{name} production component"
        )
        source = str(component["source"])
        if source not in sources:
            choices = ", ".join(sources)
            raise ValueError(
                f"{name} production names unknown source {source!r}; "
                f"choose from {choices}"
            )
        components.append(
            AssemblyComponent(source=source, weight=float(component.get("weight", 1.0)))
        )
    if operation != "mixture" and len(components) != 1:
        raise ValueError(
            f"{name} {operation} production requires exactly one component"
        )
    weights = [component.weight for component in components]
    if any(not math.isfinite(weight) or weight < 0.0 for weight in weights):
        raise ValueError(f"{name} production component weights must be finite and >= 0")
    if sum(weights) <= 0.0:
        raise ValueError(f"{name} production component weights must sum to > 0")

    epsilon_raw = raw.get("uniform_redshift_fraction")
    epsilon = None if epsilon_raw is None else float(epsilon_raw)
    if allow_proposal_density:
        if epsilon is None:
            raise ValueError(f"{name} production must define uniform_redshift_fraction")
        if not 0.0 < epsilon < 1.0:
            raise ValueError(
                f"{name} uniform_redshift_fraction must satisfy 0 < epsilon < 1"
            )
        normalized = [weight / sum(weights) for weight in weights]
        if len(normalized) != 2 or not math.isclose(
            normalized[1], epsilon, rel_tol=0.0, abs_tol=1e-12
        ):
            raise ValueError(
                f"{name} component weights must match uniform_redshift_fraction"
            )
    elif epsilon is not None:
        raise ValueError(
            f"{name} injection production cannot define uniform_redshift_fraction"
        )

    num_samples = int(raw["num_samples"])
    if num_samples <= 0:
        raise ValueError(f"{name} production num_samples must be > 0")
    return ProductionPopulationRecipe(
        operation=operation,
        num_samples=num_samples,
        seed=int(raw["seed"]),
        components=tuple(components),
        uniform_redshift_fraction=epsilon,
    )


def _waveform_from_mapping(raw: Mapping[str, Any]) -> WaveformRecipe:
    return WaveformRecipe(
        approximant=str(raw["approximant"]),
        sampling_frequency=float(raw["sampling_frequency"]),
        minimum_frequency=float(raw["minimum_frequency"]),
        maximum_frequency=float(raw["maximum_frequency"]),
        reference_frequency=float(raw["reference_frequency"]),
        frequency_resolution=float(raw["frequency_resolution"]),
        chunk_size=int(raw["chunk_size"]),
    )
