"""Generate a polarization-power catalog from its request, or reuse a cached one.

A catalog is fully determined by a :class:`~astrogwb.metadata.CatalogRequest`:
the waveform settings, the population record with its seed, the
hyperparameters and size of the draw, and the ``astrogwb`` version that ran
it. :func:`generate` turns a request into a catalog; :func:`load_or_generate`
first looks for one already saved under the request's key.

The cache is content-addressed: a catalog lives at ``<cache_dir>/<key>.h5``,
so asking for the same thing twice finds the same file and changing anything
-- a seed, a kwarg, the package version -- names a different one. There is no
index to keep in sync. A hit is still checked against the file's own record,
which catches a file copied or renamed into the wrong place.
"""

from __future__ import annotations

import logging
import os
import tempfile
from pathlib import Path

import jax

from astrogwb import __version__
from astrogwb.catalog.polarization_power import PolarizationPowerCatalog
from astrogwb.metadata import CatalogRequest
from astrogwb.utils.sampling import sample_sources

__all__ = [
    "catalog_path",
    "check_catalog_answers",
    "generate",
    "load_or_generate",
    "save_atomically",
]

logger = logging.getLogger(__name__)


def catalog_path(request: CatalogRequest, cache_dir: str | Path) -> Path:
    """Where ``request``'s catalog lives in ``cache_dir``."""
    return Path(cache_dir) / f"{request.key()}.h5"


def generate(request: CatalogRequest) -> PolarizationPowerCatalog:
    """Draw the population, generate its polarization power, and record both.

    Values are checked once, on the concrete draw: generation is trace-safe
    and trusts its inputs, so a population carrying a degree of freedom the
    approximant cannot represent would otherwise be silently dropped.
    """
    # x64 must be on before the draw. The population is sampled before the
    # Ripple-backed generator is built, and importing ripplegw -- which turns
    # this on globally -- happens only inside that generator, so relying on it
    # would draw and persist every source column in float32.
    jax.config.update("jax_enable_x64", True)

    if request.version != __version__:
        raise ValueError(
            f"request is for astrogwb {request.version}, but {__version__} is "
            "installed; a catalog is generated by the code its key names"
        )

    population = request.metadata.population
    source_model = population.build().source_model
    logger.info(
        "Catalog %s: population=%s seed=%d num_samples=%d kwargs=%s",
        request.key(),
        population.model_name,
        population.seed,
        request.num_samples,
        population.model_kwargs,
    )
    samples = sample_sources(
        source_model,
        jax.random.PRNGKey(population.seed),
        request.fiducials,
        num_samples=request.num_samples,
    )

    generator = request.metadata.waveform.build()
    logger.info(
        "Generating %s waveforms for %d events (f_min=%.1f Hz, f_max=%.1f Hz)",
        generator.metadata.approximant,
        request.num_samples,
        generator.metadata.minimum_frequency,
        generator.metadata.maximum_frequency,
    )
    generator.check_sources(samples)
    return PolarizationPowerCatalog.from_generator(
        samples,
        generator=generator,
        population=population,
        fiducials=request.fiducials,
    )


def save_atomically(catalog: PolarizationPowerCatalog, path: str | Path) -> None:
    """Write ``catalog`` to ``path`` without ever exposing a partial file.

    The file is written beside its destination and renamed into place, so a
    reader -- or a second writer racing on the same key -- sees either no file
    or a complete one. Two racing writers produce the same bytes, so the last
    rename winning is harmless.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.stem}.", suffix=".h5.tmp"
    )
    os.close(handle)
    try:
        catalog.save(temporary)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


def load_or_generate(
    request: CatalogRequest, cache_dir: str | Path
) -> PolarizationPowerCatalog:
    """Return ``request``'s catalog from ``cache_dir``, generating it on a miss.

    A hit is loaded and its recorded request compared with ``request``; a
    mismatch raises rather than serving a catalog of something else. A miss is
    generated and saved atomically under the request's key.
    """
    path = catalog_path(request, cache_dir)
    if path.is_file():
        catalog = PolarizationPowerCatalog.load(path)
        check_catalog_answers(catalog, request, label=str(path))
        logger.info("Catalog %s: cache hit at %s", request.key(), path)
        return catalog

    logger.info("Catalog %s: cache miss, generating into %s", request.key(), path)
    catalog = generate(request)
    save_atomically(catalog, path)
    return catalog


def check_catalog_answers(
    catalog: PolarizationPowerCatalog, request: CatalogRequest, *, label: str
) -> None:
    """Raise unless ``catalog`` records exactly what ``request`` asks for."""
    recorded = CatalogRequest.from_catalog(catalog)
    if recorded.key() != request.key():
        raise ValueError(
            f"{label} records catalog {recorded.key()}, not the requested "
            f"{request.key()}:\n  recorded:  {recorded.model_dump_json()}\n"
            f"  requested: {request.model_dump_json()}"
        )
