"""Turn a :class:`~astrogwb.metadata.CatalogMetadata` into a polarization-power catalog.

:class:`CatalogGenerator` is the generator half of
:func:`astrogwb.catalog.simulate` for catalogs, as
:class:`~astrogwb.catalog.SpectrumGenerator` is for spectra: it draws the
population the record names at its fiducials, generates the waveform power,
and returns a catalog that carries the record.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import ClassVar

import jax

from astrogwb import __version__
from astrogwb.catalog.polarization_power import PolarizationPowerCatalog
from astrogwb.metadata import CatalogMetadata
from astrogwb.sampling.utils import sample_sources

__all__ = ["CatalogGenerator"]

logger = logging.getLogger(__name__)


@dataclass(frozen=True, slots=True)
class CatalogGenerator:
    """Draw the catalog a :class:`~astrogwb.metadata.CatalogMetadata` describes.

    It holds no settings: everything that changes a catalog is in the record,
    so every generator answers the same metadata with the same file.
    """

    #: What this generator produces, and what :func:`astrogwb.catalog.simulate`
    #: loads a cache hit as.
    artifact: ClassVar[type[PolarizationPowerCatalog]] = PolarizationPowerCatalog

    def __call__(self, metadata: CatalogMetadata) -> PolarizationPowerCatalog:
        """Draw the population, generate its polarization power, and record both.

        Values are checked once, on the concrete draw: generation is trace-safe
        and trusts its inputs, so a population carrying a degree of freedom the
        approximant cannot represent would otherwise be silently dropped.
        """
        # x64 must be on before the draw. The population is sampled before the
        # Ripple-backed generator is built, and importing ripplegw -- which
        # turns this on globally -- happens only inside that generator, so
        # relying on it would draw and persist every source column in float32.
        jax.config.update("jax_enable_x64", True)

        if metadata.version != __version__:
            raise ValueError(
                f"metadata is for astrogwb {metadata.version}, but {__version__} "
                "is installed; a catalog is generated by the code its key names"
            )

        population = metadata.population
        logger.info(
            "Catalog %s: population=%s seed=%d num_samples=%d kwargs=%s",
            metadata.key(),
            population.model_name,
            population.seed,
            metadata.num_samples,
            population.model_kwargs,
        )
        samples = sample_sources(
            population.build().source_model,
            jax.random.PRNGKey(population.seed),
            metadata.fiducials,
            num_samples=metadata.num_samples,
        )

        generator = metadata.waveform.build()
        logger.info(
            "Generating %s waveforms for %d events (f_min=%.1f Hz, f_max=%.1f Hz)",
            generator.metadata.approximant,
            metadata.num_samples,
            generator.metadata.minimum_frequency,
            generator.metadata.maximum_frequency,
        )
        generator.check_sources(samples)
        return self.artifact.from_generator(
            samples,
            generator=generator,
            population=population,
            fiducials=metadata.fiducials,
        )
