"""Per-source waveform power as a catalog, and the plain catalog draw.

:func:`polarization_power_data` turns a generator and source columns into
:class:`PolarizationPowerData`, one power column per source; where the sources
come from is the caller's. :func:`draw_catalog` is the plain catalog -- the
population a :class:`~astrogwb.simulators.polarization_power.CatalogMetadata`
names, drawn at its fiducials from one key -- and :mod:`astrogwb.gwb.importance`
places the same draw at redshift nodes.
:func:`~astrogwb.simulators.polarization_power.restrict_redshift` narrows a
plain catalog and its record together.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping
from functools import partial
from typing import Any, TypedDict

import jax
import numpy as np
from numpy.typing import ArrayLike, NDArray

from astrogwb import __version__
from astrogwb.populations.evaluation import sample_sources
from astrogwb.simulators.polarization_power.metadata import CatalogMetadata
from astrogwb.waveform.generator.base import PolarizationPowerGenerator

__all__ = ["PolarizationPowerData", "draw_catalog", "polarization_power_data"]

logger = logging.getLogger(__name__)


class PolarizationPowerData(TypedDict):
    """One catalog: ``frequencies`` ``(F,)``, ``polarization_power`` ``(F, N)``.

    ``source_parameters`` columns are each ``(N,)``.
    """

    frequencies: NDArray[np.float64]
    polarization_power: NDArray[np.float64]
    source_parameters: dict[str, NDArray[Any]]


def polarization_power_data(
    generator: PolarizationPowerGenerator,
    source_parameters: Mapping[str, ArrayLike],
    *,
    chunk_size: int | None = None,
) -> PolarizationPowerData:
    """The power of ``source_parameters`` as a catalog, generated eagerly.

    Values are checked once, on the concrete sources: generation is trace-safe
    and trusts its inputs, so a source carrying a degree of freedom the
    approximant cannot represent would otherwise be silently dropped. The
    columns are passed through as arrays; ``chunk_size`` is
    :meth:`~astrogwb.waveform.PolarizationPowerGenerator.generate_batch`'s.
    """
    # Power is float64 throughout; see draw_catalog for why sources too.
    jax.config.update("jax_enable_x64", True)
    columns = {name: np.asarray(values) for name, values in source_parameters.items()}
    logger.info(
        "Generating %s waveforms for %d events (f_min=%.1f Hz, f_max=%.1f Hz)",
        generator.metadata.approximant,
        len(next(iter(columns.values()))),
        generator.metadata.minimum_frequency,
        generator.metadata.maximum_frequency,
    )
    generator.check_sources(columns)
    # Generators are deliberately jit-free so they compose inside NumPyro
    # models. This is the opposite case -- eager and whole-catalog -- and at
    # production sizes an unfused graph would hold every waveform intermediate
    # at once, so the jit belongs here.
    power = jax.jit(partial(generator.generate_batch, chunk_size=chunk_size))
    return {
        "frequencies": np.asarray(generator.frequencies),
        "polarization_power": np.asarray(power(columns)),
        "source_parameters": columns,
    }


def draw_catalog(
    metadata: CatalogMetadata, key: jax.Array, *, chunk_size: int | None = None
) -> PolarizationPowerData:
    """The plain catalog ``key`` draws: ``num_samples`` sources at the fiducials.

    The key is an input, so one record serves any number of independent
    realizations.
    """
    # x64 must be on before the draw. The population is sampled before the
    # Ripple-backed generator runs, and importing ripplegw -- which turns this
    # on globally -- happens only inside that generator, so relying on it would
    # draw every source column in float32.
    jax.config.update("jax_enable_x64", True)
    if metadata.version != __version__:
        raise ValueError(
            f"metadata is for astrogwb {metadata.version}, but {__version__} "
            "is installed; a catalog is generated by the code its key names"
        )
    logger.info(
        "Catalog %s: population=%s num_samples=%d kwargs=%s",
        metadata.key(),
        metadata.population.model_name,
        metadata.num_samples,
        metadata.population.model_kwargs,
    )
    _, model = metadata.population.build()(metadata.fiducials)
    samples = sample_sources(model, key, num_samples=metadata.num_samples)
    return polarization_power_data(
        metadata.waveform.build(), samples, chunk_size=chunk_size
    )
