"""The simulator that draws a polarization-power catalog.

:class:`PolarizationPowerSimulator` draws the population a
:class:`~astrogwb.simulators.polarization_power.CatalogMetadata` names at its
fiducials, generates the waveform power of every source, and returns the
:class:`PolarizationPowerData`; its metadata travels beside it, and
:func:`~astrogwb.simulators.polarization_power.restrict_redshift` narrows the pair. The key is an input, so one metadata record serves any number of
independent realizations.
"""

from __future__ import annotations

import logging
from typing import Any, TypedDict

import jax
import numpy as np
from numpy.typing import NDArray

from astrogwb import __version__
from astrogwb.populations.evaluation import sample_sources
from astrogwb.simulators.polarization_power.metadata import CatalogMetadata

__all__ = ["PolarizationPowerData", "PolarizationPowerSimulator"]

logger = logging.getLogger(__name__)


class PolarizationPowerData(TypedDict):
    """One catalog: ``frequencies`` ``(F,)``, ``polarization_power`` ``(F, N)``.

    ``source_parameters`` columns are each ``(N,)``.
    """

    frequencies: NDArray[np.float64]
    polarization_power: NDArray[np.float64]
    source_parameters: dict[str, NDArray[Any]]


class PolarizationPowerSimulator:
    """Draws catalogs for one :class:`CatalogMetadata`; build once, call often.

    ``simulator(key)`` draws ``metadata.num_samples`` sources at the fiducials and
    their waveform power: one catalog per key, vectorized over its events.
    Values are checked once, on the concrete draw: generation is trace-safe and
    trusts its inputs, so a population carrying a degree of freedom the
    approximant cannot represent would otherwise be silently dropped.

    ``chunk_size`` is a cost-only setting: the waveform power is generated
    ``chunk_size`` sources at a time (the last chunk padded to the same shape, so
    one compilation serves all), which bounds peak memory without changing the
    catalog. ``None`` generates the whole catalog in one call.
    """

    def __init__(
        self, metadata: CatalogMetadata, *, chunk_size: int | None = 16_384
    ) -> None:
        if chunk_size is not None and chunk_size < 1:
            raise ValueError(f"chunk_size must be positive, got {chunk_size}")
        # x64 must be on before the draw. The population is sampled before the
        # Ripple-backed generator is built, and importing ripplegw -- which turns
        # this on globally -- happens only inside that generator, so relying on
        # it would draw every source column in float32.
        jax.config.update("jax_enable_x64", True)

        if metadata.version != __version__:
            raise ValueError(
                f"metadata is for astrogwb {metadata.version}, but {__version__} "
                "is installed; a catalog is generated by the code its key names"
            )
        self._metadata = metadata
        self._chunk_size = chunk_size
        self._population = metadata.population.build()
        self._generator = metadata.waveform.build()
        # Generators are deliberately jit-free so they compose inside NumPyro
        # models. This simulator is the opposite case -- eager and
        # whole-catalog -- and at production sizes an unfused graph would hold
        # every waveform intermediate at once, so the jit belongs here.
        self._power = jax.jit(self._generator.generate_batch)

    @property
    def metadata(self) -> CatalogMetadata:
        """The record this simulator draws."""
        return self._metadata

    def __call__(self, key: jax.Array) -> PolarizationPowerData:
        """The catalog ``key`` draws."""
        metadata = self._metadata
        logger.info(
            "Catalog %s: population=%s num_samples=%d kwargs=%s",
            metadata.key(),
            metadata.population.model_name,
            metadata.num_samples,
            metadata.population.model_kwargs,
        )
        _, model = self._population(metadata.fiducials)
        samples = sample_sources(model, key, num_samples=metadata.num_samples)
        generator = self._generator
        logger.info(
            "Generating %s waveforms for %d events (f_min=%.1f Hz, f_max=%.1f Hz)",
            generator.metadata.approximant,
            metadata.num_samples,
            generator.metadata.minimum_frequency,
            generator.metadata.maximum_frequency,
        )
        generator.check_sources(samples)
        parameters: dict[str, Any] = {
            name: np.asarray(values) for name, values in samples.items()
        }
        return {
            "frequencies": np.asarray(generator.frequencies),
            "polarization_power": self._chunked_power(samples),
            "source_parameters": parameters,
        }

    def _chunked_power(self, samples: dict[str, Any]) -> NDArray[np.float64]:
        """``(F, N)`` power of ``samples``, generated ``chunk_size`` sources at a time."""
        num_samples = self._metadata.num_samples
        chunk_size = self._chunk_size
        if chunk_size is None or chunk_size >= num_samples:
            return np.asarray(self._power(samples))
        columns = {name: np.asarray(values) for name, values in samples.items()}
        power: NDArray[np.float64] | None = None
        for start in range(0, num_samples, chunk_size):
            stop = min(start + chunk_size, num_samples)
            # Pad the tail with its own last source so every chunk shares one shape.
            index = np.minimum(np.arange(start, start + chunk_size), num_samples - 1)
            chunk = np.asarray(
                self._power({name: values[index] for name, values in columns.items()})
            )
            if power is None:
                power = np.empty((chunk.shape[0], num_samples), dtype=chunk.dtype)
            power[:, start:stop] = chunk[:, : stop - start]
        assert power is not None
        return power
