"""The cached node that draws a polarization-power catalog.

:func:`polarization_power` draws the population a
:class:`~astrogwb.simulators.polarization_power.CatalogMetadata` names at its
fiducials, generates the waveform power of every source, and returns the arrays
:meth:`PolarizationPowerCatalog.from_arrays
<astrogwb.simulators.polarization_power.PolarizationPowerCatalog.from_arrays>`
wraps. The seed is an input, so one metadata record serves any number of
independent realizations.
"""

from __future__ import annotations

import logging
from typing import Any

import numpy as np

from astrogwb import __version__
from astrogwb.simulators.core import Arrays, Tree, cached
from astrogwb.simulators.polarization_power.metadata import CatalogMetadata

__all__ = ["polarization_power", "scalar_seed"]

logger = logging.getLogger(__name__)


def scalar_seed(inputs: Tree) -> np.uint64:
    """The ``seed`` input, required to be a 0-d ``uint64``."""
    seed = np.asarray(inputs["seed"])
    if seed.ndim != 0 or seed.dtype != np.uint64:
        raise TypeError(
            "inputs['seed'] must be a 0-d uint64 array, e.g. np.uint64(41); got "
            f"dtype={seed.dtype} shape={seed.shape}"
        )
    return np.uint64(seed.item())


@cached
def polarization_power(inputs: Tree, metadata: CatalogMetadata) -> Arrays:
    """Draw the catalog ``metadata`` describes at ``inputs["seed"]``.

    Returns ``frequencies`` ``(F,)``, ``polarization_power`` ``(F, N)`` and the
    ``source_parameters`` columns, each ``(N,)``. Values are checked once, on
    the concrete draw: generation is trace-safe and trusts its inputs, so a
    population carrying a degree of freedom the approximant cannot represent
    would otherwise be silently dropped.
    """
    import jax

    # x64 must be on before the draw. The population is sampled before the
    # Ripple-backed generator is built, and importing ripplegw -- which turns
    # this on globally -- happens only inside that generator, so relying on it
    # would draw and persist every source column in float32.
    jax.config.update("jax_enable_x64", True)

    from astrogwb.populations.evaluation import sample_sources
    from astrogwb.simulators._keys import seed_key

    if metadata.version != __version__:
        raise ValueError(
            f"metadata is for astrogwb {metadata.version}, but {__version__} "
            "is installed; a catalog is generated by the code its key names"
        )
    seed = scalar_seed(inputs)

    population = metadata.population
    logger.info(
        "Catalog %s: population=%s seed=%d num_samples=%d kwargs=%s",
        metadata.key(),
        population.model_name,
        seed,
        metadata.num_samples,
        population.model_kwargs,
    )
    samples = sample_sources(
        population.build().source_model,
        seed_key(seed),
        metadata.fiducials,
        num_samples=metadata.num_samples,
    )

    generator = metadata.waveform.build()
    logger.info(
        "Generating %s waveforms for %d events (f_min=%.1f Hz, f_max=%.1f Hz)",
        generator.metadata.approximant,
        metadata.num_samples,
        generator.metadata.minimum_frequency,
        generator.metadata.maximum_frequency,
    )
    generator.check_sources(samples)
    # Generators are deliberately jit-free so they compose inside NumPyro
    # models. This node is the opposite case -- eager and whole-catalog -- and
    # at production sizes an unfused graph would hold every waveform
    # intermediate at once, so the jit belongs here.
    power = jax.jit(generator.generate_batch)(samples)
    parameters: dict[str, Any] = {
        name: np.asarray(values) for name, values in samples.items()
    }
    return {
        "frequencies": np.asarray(generator.frequencies),
        "polarization_power": np.asarray(power),
        "source_parameters": parameters,
    }
