"""The cached node that draws populations: hyperparameters, counts, sources.

:func:`population` is the waveform-free half of the spectra forward model. It
returns the draws flat -- ``source_parameters`` columns of length
``counts.sum()`` -- so a consumer reduces them without padding each draw to the
largest; :class:`~astrogwb.simulators.population.PopulationDraws` names the
layout. Persisting a draw pays when it is reused, such as two waveform
approximants on the same sources; a throwaway simulation loop calls
:class:`~astrogwb.simulators.population.PopulationSampler` and keeps nothing.
"""

from __future__ import annotations

import logging
from typing import Any

from astrogwb import __version__
from astrogwb.simulators.core import Arrays, Tree, cached, validate_seeds
from astrogwb.simulators.population.draws import PopulationSampler
from astrogwb.simulators.population.metadata import PopulationDrawMetadata

__all__ = ["build_sampler", "population"]

logger = logging.getLogger(__name__)


def build_sampler(metadata: PopulationDrawMetadata) -> PopulationSampler:
    """The live sampler ``metadata`` names; build once and reuse across calls."""
    built = metadata.population.build()
    return PopulationSampler(
        source_model=built.source_model,
        merger_rate_fn=built.merger_rate_fn,
        fixed=metadata.fixed,
        priors={name: spec.build() for name, spec in metadata.sampled.items()},
        observation_time=metadata.observation_time,
        count=metadata.count,
        num_events=metadata.num_events,
    )


@cached
def population(
    inputs: Tree, metadata: PopulationDrawMetadata, *, chunk_size: int = 128
) -> Arrays:
    """Draw one population per seed in ``inputs["seeds"]``.

    ``chunk_size`` sets the ladder of sizes sources are drawn at, so it changes
    cost and compilation but not the draws: event ``i`` of a draw comes from a
    key folded with ``i``. Returns ``total_merger_rate`` ``(D,)``, ``counts``
    ``(D,)``, one ``hyperparameters`` column ``(D,)`` per declared
    hyperparameter and the flat ``source_parameters`` columns
    ``(counts.sum(),)``.
    """
    import jax

    # x64 before any array: seeds are 64-bit and the rate must not depend on a
    # waveform import turning it on as a side effect.
    jax.config.update("jax_enable_x64", True)

    if chunk_size <= 0:
        raise ValueError("chunk_size must be positive")
    if metadata.version != __version__:
        raise ValueError(
            f"metadata is for astrogwb {metadata.version}, but {__version__} "
            "is installed; draws are generated by the code their key names"
        )
    seeds = validate_seeds(inputs)
    logger.info(
        "Population %s: count=%s num_events=%s population=%s draws=%d sampled=%s",
        metadata.key(),
        metadata.count,
        metadata.num_events,
        metadata.population.model_name,
        seeds.size,
        sorted(metadata.sampled),
    )
    draws = build_sampler(metadata)(seeds, chunk_size=chunk_size)
    hyperparameters: dict[str, Any] = dict(draws.hyperparameters)
    source_parameters: dict[str, Any] = dict(draws.source_parameters)
    return {
        "total_merger_rate": draws.total_merger_rate,
        "counts": draws.counts,
        "hyperparameters": hyperparameters,
        "source_parameters": source_parameters,
    }
