"""The simulator that draws populations: hyperparameters, counts, sources.

:class:`PopulationSimulator` is the waveform-free half of the spectra forward
model. Its batched layout is *flat and ragged* -- ``source_parameters`` columns
of length ``counts.sum()`` -- so a consumer reduces draws without padding each to
the largest; :class:`~astrogwb.simulators.population.PopulationData` names it.
Persisting a draw pays when it is reused, such as two waveform approximants on
the same sources.
"""

from __future__ import annotations

from typing import Any

import jax
import numpy as np

from astrogwb import __version__
from astrogwb.simulators.population.draws import PopulationData, PopulationSampler
from astrogwb.simulators.population.metadata import PopulationDrawMetadata

__all__ = ["PopulationSimulator"]


class PopulationSimulator:
    """Draws populations for one :class:`PopulationDrawMetadata`; build once, call often.

    ``simulate(key)`` is one draw -- scalar ``total_merger_rate`` and ``counts``,
    scalar hyperparameters, ``(count,)`` source columns -- and
    ``simulate_batch(keys)`` is ``D`` draws in the flat layout of
    :class:`~astrogwb.simulators.population.PopulationData`. Draw ``i`` of the
    batch is ``simulate(keys[i])``: a draw depends on its own key alone, and
    event ``j`` comes from a key folded with ``j``. ``chunk_size`` sets the ladder
    of sizes sources are drawn at, so it changes cost and compilation, not the
    draw, which is why it is a setting and not metadata. Keys come from
    :func:`~astrogwb.simulators.core.batch_keys`.

    The simulator holds the jitted stages, so reusing one keeps their
    compilations warm.
    """

    def __init__(
        self, metadata: PopulationDrawMetadata, *, chunk_size: int = 128
    ) -> None:
        # x64 before any array: keys are built from 64-bit seeds and the rate
        # must not depend on a waveform import turning it on as a side effect.
        jax.config.update("jax_enable_x64", True)

        if chunk_size <= 0:
            raise ValueError("chunk_size must be positive")
        if metadata.version != __version__:
            raise ValueError(
                f"metadata is for astrogwb {metadata.version}, but {__version__} "
                "is installed; draws are generated by the code their key names"
            )
        built = metadata.population.build()
        self._metadata = metadata
        self._chunk_size = chunk_size
        self._sampler = PopulationSampler(
            source_model=built.source_model,
            merger_rate_fn=built.merger_rate_fn,
            fixed=metadata.fixed,
            priors={name: spec.build() for name, spec in metadata.sampled.items()},
            observation_time=metadata.observation_time,
            count=metadata.count,
            num_events=metadata.num_events,
        )

    @property
    def metadata(self) -> PopulationDrawMetadata:
        """The record this simulator draws."""
        return self._metadata

    @property
    def observation_seconds(self) -> float:
        """The observation time in seconds, as Poisson counts use it."""
        return self._sampler.observation_seconds

    def simulate_batch(self, keys: jax.Array) -> PopulationData:
        """One population per key, in the flat layout of :class:`PopulationData`."""
        if keys.ndim != 1 or keys.shape[0] == 0:
            raise ValueError(
                f"keys must be a non-empty 1-d batch of keys, got shape {keys.shape}"
            )
        return self._sampler(keys, chunk_size=self._chunk_size).as_data()

    def simulate(self, key: jax.Array) -> PopulationData:
        """The population ``key`` draws: scalars, and ``(count,)`` source columns."""
        batch = self.simulate_batch(key[None])
        hyperparameters: dict[str, Any] = {
            name: np.asarray(column)[0]
            for name, column in batch["hyperparameters"].items()
        }
        return {
            "total_merger_rate": np.asarray(batch["total_merger_rate"])[0],
            "counts": np.asarray(batch["counts"])[0],
            "hyperparameters": hyperparameters,
            "source_parameters": batch["source_parameters"],
        }
